export const TEAM_NAMES: Record<string, string> = {
  MEX: "México",
  RSA: "África do Sul",
  KOR: "Coreia do Sul",
  CZE: "Rep. Tcheca",
  CAN: "Canadá",
  BIH: "Bósnia",
  QAT: "Catar",
  SUI: "Suíça",
  BRA: "Brasil",
  MAR: "Marrocos",
  HAI: "Haiti",
  SCO: "Escócia",
  USA: "Estados Unidos",
  PAR: "Paraguai",
  AUS: "Austrália",
  TUR: "Turquia",
  GER: "Alemanha",
  CUW: "Curaçao",
  CIV: "Costa do Marfim",
  ECU: "Equador",
  NED: "Holanda",
  JPN: "Japão",
  SWE: "Suécia",
  TUN: "Tunísia",
  BEL: "Bélgica",
  EGY: "Egito",
  IRN: "Irã",
  NZL: "Nova Zelândia",
  ESP: "Espanha",
  CPV: "Cabo Verde",
  KSA: "Arábia Saudita",
  URU: "Uruguai",
  FRA: "França",
  SEN: "Senegal",
  IRQ: "Iraque",
  NOR: "Noruega",
  ARG: "Argentina",
  ALG: "Argélia",
  AUT: "Áustria",
  JOR: "Jordânia",
  POR: "Portugal",
  COD: "Congo",
  UZB: "Uzbequistão",
  COL: "Colômbia",
  ENG: "Inglaterra",
  CRO: "Croácia",
  GHA: "Gana",
  PAN: "Panamá",
};

export function getTeamName(slug: string | null): string {
  if (!slug) return "Especial";
  return TEAM_NAMES[slug] ?? slug;
}
