-- Seed: stickers (994 figurinhas FIFA 2026)
-- 48 seleções × 20 = 960 (national_team, is_official_album=true)
-- 20 figurinhas FWC (tournament_special, is_official_album=true)
-- 14 figurinhas CC (promotional, is_official_album=false)
-- Idempotente via ON CONFLICT DO NOTHING

-- FWC: Tournament Special (FWC0–FWC19)
INSERT INTO stickers (natural_key, section_type, team_slug, group_code, position_in_section, position_role, sticker_name, is_official_album, release_batch, rarity) VALUES
('FWC0',  'tournament_special', NULL, NULL, 0,  'intro',   'FIFA World Cup 2026 Opening',        TRUE, 'original', 'regular'),
('FWC1',  'tournament_special', NULL, NULL, 1,  'intro',   'FIFA World Cup 2026 Trophy',          TRUE, 'original', 'regular'),
('FWC2',  'tournament_special', NULL, NULL, 2,  'intro',   'FIFA World Cup 2026 Host Cities',     TRUE, 'original', 'regular'),
('FWC3',  'tournament_special', NULL, NULL, 3,  'intro',   'FIFA World Cup 2026 Stadiums',        TRUE, 'original', 'regular'),
('FWC4',  'tournament_special', NULL, NULL, 4,  'intro',   'FIFA World Cup 2026 Logo',            TRUE, 'original', 'regular'),
('FWC5',  'tournament_special', NULL, NULL, 5,  'intro',   'FIFA World Cup 2026 Ball',            TRUE, 'original', 'regular'),
('FWC6',  'tournament_special', NULL, NULL, 6,  'intro',   'FIFA World Cup 2026 Mascot',          TRUE, 'original', 'regular'),
('FWC7',  'tournament_special', NULL, NULL, 7,  'intro',   'FIFA World Cup 2026 Legends',         TRUE, 'original', 'regular'),
('FWC8',  'tournament_special', NULL, NULL, 8,  'intro',   'FIFA World Cup 2026 History',         TRUE, 'original', 'regular'),
('FWC9',  'tournament_special', NULL, NULL, 9,  'history', 'FWC History 1930',                    TRUE, 'original', 'regular'),
('FWC10', 'tournament_special', NULL, NULL, 10, 'history', 'FWC History 1950',                    TRUE, 'original', 'regular'),
('FWC11', 'tournament_special', NULL, NULL, 11, 'history', 'FWC History 1958',                    TRUE, 'original', 'regular'),
('FWC12', 'tournament_special', NULL, NULL, 12, 'history', 'FWC History 1970',                    TRUE, 'original', 'regular'),
('FWC13', 'tournament_special', NULL, NULL, 13, 'history', 'FWC History 1986',                    TRUE, 'original', 'regular'),
('FWC14', 'tournament_special', NULL, NULL, 14, 'history', 'FWC History 1994',                    TRUE, 'original', 'regular'),
('FWC15', 'tournament_special', NULL, NULL, 15, 'history', 'FWC History 1998',                    TRUE, 'original', 'regular'),
('FWC16', 'tournament_special', NULL, NULL, 16, 'history', 'FWC History 2006',                    TRUE, 'original', 'regular'),
('FWC17', 'tournament_special', NULL, NULL, 17, 'history', 'FWC History 2010',                    TRUE, 'original', 'regular'),
('FWC18', 'tournament_special', NULL, NULL, 18, 'history', 'FWC History 2014',                    TRUE, 'original', 'regular'),
('FWC19', 'tournament_special', NULL, NULL, 19, 'history', 'FWC History 2022',                    TRUE, 'original', 'regular')
ON CONFLICT (natural_key) DO NOTHING;

-- CC: Coca-Cola Promotional (CC0–CC13), is_official_album=false
INSERT INTO stickers (natural_key, section_type, team_slug, group_code, position_in_section, position_role, sticker_name, is_official_album, release_batch, rarity) VALUES
('CC0',  'promotional', NULL, NULL, 0,  'promo', 'Coca-Cola FIFA 2026 Promo 1',  FALSE, 'coca_cola', 'regular'),
('CC1',  'promotional', NULL, NULL, 1,  'promo', 'Coca-Cola FIFA 2026 Promo 2',  FALSE, 'coca_cola', 'regular'),
('CC2',  'promotional', NULL, NULL, 2,  'promo', 'Coca-Cola FIFA 2026 Promo 3',  FALSE, 'coca_cola', 'regular'),
('CC3',  'promotional', NULL, NULL, 3,  'promo', 'Coca-Cola FIFA 2026 Promo 4',  FALSE, 'coca_cola', 'regular'),
('CC4',  'promotional', NULL, NULL, 4,  'promo', 'Coca-Cola FIFA 2026 Promo 5',  FALSE, 'coca_cola', 'regular'),
('CC5',  'promotional', NULL, NULL, 5,  'promo', 'Coca-Cola FIFA 2026 Promo 6',  FALSE, 'coca_cola', 'regular'),
('CC6',  'promotional', NULL, NULL, 6,  'promo', 'Coca-Cola FIFA 2026 Promo 7',  FALSE, 'coca_cola', 'regular'),
('CC7',  'promotional', NULL, NULL, 7,  'promo', 'Coca-Cola FIFA 2026 Promo 8',  FALSE, 'coca_cola', 'regular'),
('CC8',  'promotional', NULL, NULL, 8,  'promo', 'Coca-Cola FIFA 2026 Promo 9',  FALSE, 'coca_cola', 'regular'),
('CC9',  'promotional', NULL, NULL, 9,  'promo', 'Coca-Cola FIFA 2026 Promo 10', FALSE, 'coca_cola', 'regular'),
('CC10', 'promotional', NULL, NULL, 10, 'promo', 'Coca-Cola FIFA 2026 Promo 11', FALSE, 'coca_cola', 'regular'),
('CC11', 'promotional', NULL, NULL, 11, 'promo', 'Coca-Cola FIFA 2026 Promo 12', FALSE, 'coca_cola', 'regular'),
('CC12', 'promotional', NULL, NULL, 12, 'promo', 'Coca-Cola FIFA 2026 Promo 13', FALSE, 'coca_cola', 'regular'),
('CC13', 'promotional', NULL, NULL, 13, 'promo', 'Coca-Cola FIFA 2026 Promo 14', FALSE, 'coca_cola', 'regular')
ON CONFLICT (natural_key) DO NOTHING;

-- National Teams (48 teams × 20 stickers each = 960)
-- Position 1: badge, Position 13: team_photo, Positions 2-12,14-20: player
-- Groups A-L with 4 teams each = 48 teams

-- GROUP A: Qatar, Ecuador, Senegal, Netherlands
INSERT INTO stickers (natural_key, section_type, team_slug, group_code, position_in_section, position_role, sticker_name, is_official_album, release_batch, rarity) VALUES
('QAT1','national_team','QAT','A',1,'badge','Qatar Badge',TRUE,'original','regular'),
('QAT2','national_team','QAT','A',2,'player','Qatar Player 2',TRUE,'original','regular'),
('QAT3','national_team','QAT','A',3,'player','Qatar Player 3',TRUE,'original','regular'),
('QAT4','national_team','QAT','A',4,'player','Qatar Player 4',TRUE,'original','regular'),
('QAT5','national_team','QAT','A',5,'player','Qatar Player 5',TRUE,'original','regular'),
('QAT6','national_team','QAT','A',6,'player','Qatar Player 6',TRUE,'original','regular'),
('QAT7','national_team','QAT','A',7,'player','Qatar Player 7',TRUE,'original','regular'),
('QAT8','national_team','QAT','A',8,'player','Qatar Player 8',TRUE,'original','regular'),
('QAT9','national_team','QAT','A',9,'player','Qatar Player 9',TRUE,'original','regular'),
('QAT10','national_team','QAT','A',10,'player','Qatar Player 10',TRUE,'original','regular'),
('QAT11','national_team','QAT','A',11,'player','Qatar Player 11',TRUE,'original','regular'),
('QAT12','national_team','QAT','A',12,'player','Qatar Player 12',TRUE,'original','regular'),
('QAT13','national_team','QAT','A',13,'team_photo','Qatar Team Photo',TRUE,'original','regular'),
('QAT14','national_team','QAT','A',14,'player','Qatar Player 14',TRUE,'original','regular'),
('QAT15','national_team','QAT','A',15,'player','Qatar Player 15',TRUE,'original','regular'),
('QAT16','national_team','QAT','A',16,'player','Qatar Player 16',TRUE,'original','regular'),
('QAT17','national_team','QAT','A',17,'player','Qatar Player 17',TRUE,'original','regular'),
('QAT18','national_team','QAT','A',18,'player','Qatar Player 18',TRUE,'original','regular'),
('QAT19','national_team','QAT','A',19,'player','Qatar Player 19',TRUE,'original','regular'),
('QAT20','national_team','QAT','A',20,'player','Qatar Player 20',TRUE,'original','regular'),
('ECU1','national_team','ECU','A',1,'badge','Ecuador Badge',TRUE,'original','regular'),
('ECU2','national_team','ECU','A',2,'player','Ecuador Player 2',TRUE,'original','regular'),
('ECU3','national_team','ECU','A',3,'player','Ecuador Player 3',TRUE,'original','regular'),
('ECU4','national_team','ECU','A',4,'player','Ecuador Player 4',TRUE,'original','regular'),
('ECU5','national_team','ECU','A',5,'player','Ecuador Player 5',TRUE,'original','regular'),
('ECU6','national_team','ECU','A',6,'player','Ecuador Player 6',TRUE,'original','regular'),
('ECU7','national_team','ECU','A',7,'player','Ecuador Player 7',TRUE,'original','regular'),
('ECU8','national_team','ECU','A',8,'player','Ecuador Player 8',TRUE,'original','regular'),
('ECU9','national_team','ECU','A',9,'player','Ecuador Player 9',TRUE,'original','regular'),
('ECU10','national_team','ECU','A',10,'player','Ecuador Player 10',TRUE,'original','regular'),
('ECU11','national_team','ECU','A',11,'player','Ecuador Player 11',TRUE,'original','regular'),
('ECU12','national_team','ECU','A',12,'player','Ecuador Player 12',TRUE,'original','regular'),
('ECU13','national_team','ECU','A',13,'team_photo','Ecuador Team Photo',TRUE,'original','regular'),
('ECU14','national_team','ECU','A',14,'player','Ecuador Player 14',TRUE,'original','regular'),
('ECU15','national_team','ECU','A',15,'player','Ecuador Player 15',TRUE,'original','regular'),
('ECU16','national_team','ECU','A',16,'player','Ecuador Player 16',TRUE,'original','regular'),
('ECU17','national_team','ECU','A',17,'player','Ecuador Player 17',TRUE,'original','regular'),
('ECU18','national_team','ECU','A',18,'player','Ecuador Player 18',TRUE,'original','regular'),
('ECU19','national_team','ECU','A',19,'player','Ecuador Player 19',TRUE,'original','regular'),
('ECU20','national_team','ECU','A',20,'player','Ecuador Player 20',TRUE,'original','regular'),
('SEN1','national_team','SEN','A',1,'badge','Senegal Badge',TRUE,'original','regular'),
('SEN2','national_team','SEN','A',2,'player','Senegal Player 2',TRUE,'original','regular'),
('SEN3','national_team','SEN','A',3,'player','Senegal Player 3',TRUE,'original','regular'),
('SEN4','national_team','SEN','A',4,'player','Senegal Player 4',TRUE,'original','regular'),
('SEN5','national_team','SEN','A',5,'player','Senegal Player 5',TRUE,'original','regular'),
('SEN6','national_team','SEN','A',6,'player','Senegal Player 6',TRUE,'original','regular'),
('SEN7','national_team','SEN','A',7,'player','Senegal Player 7',TRUE,'original','regular'),
('SEN8','national_team','SEN','A',8,'player','Senegal Player 8',TRUE,'original','regular'),
('SEN9','national_team','SEN','A',9,'player','Senegal Player 9',TRUE,'original','regular'),
('SEN10','national_team','SEN','A',10,'player','Senegal Player 10',TRUE,'original','regular'),
('SEN11','national_team','SEN','A',11,'player','Senegal Player 11',TRUE,'original','regular'),
('SEN12','national_team','SEN','A',12,'player','Senegal Player 12',TRUE,'original','regular'),
('SEN13','national_team','SEN','A',13,'team_photo','Senegal Team Photo',TRUE,'original','regular'),
('SEN14','national_team','SEN','A',14,'player','Senegal Player 14',TRUE,'original','regular'),
('SEN15','national_team','SEN','A',15,'player','Senegal Player 15',TRUE,'original','regular'),
('SEN16','national_team','SEN','A',16,'player','Senegal Player 16',TRUE,'original','regular'),
('SEN17','national_team','SEN','A',17,'player','Senegal Player 17',TRUE,'original','regular'),
('SEN18','national_team','SEN','A',18,'player','Senegal Player 18',TRUE,'original','regular'),
('SEN19','national_team','SEN','A',19,'player','Senegal Player 19',TRUE,'original','regular'),
('SEN20','national_team','SEN','A',20,'player','Senegal Player 20',TRUE,'original','regular'),
('NED1','national_team','NED','A',1,'badge','Netherlands Badge',TRUE,'original','regular'),
('NED2','national_team','NED','A',2,'player','Netherlands Player 2',TRUE,'original','regular'),
('NED3','national_team','NED','A',3,'player','Netherlands Player 3',TRUE,'original','regular'),
('NED4','national_team','NED','A',4,'player','Netherlands Player 4',TRUE,'original','regular'),
('NED5','national_team','NED','A',5,'player','Netherlands Player 5',TRUE,'original','regular'),
('NED6','national_team','NED','A',6,'player','Netherlands Player 6',TRUE,'original','regular'),
('NED7','national_team','NED','A',7,'player','Netherlands Player 7',TRUE,'original','regular'),
('NED8','national_team','NED','A',8,'player','Netherlands Player 8',TRUE,'original','regular'),
('NED9','national_team','NED','A',9,'player','Netherlands Player 9',TRUE,'original','regular'),
('NED10','national_team','NED','A',10,'player','Netherlands Player 10',TRUE,'original','regular'),
('NED11','national_team','NED','A',11,'player','Netherlands Player 11',TRUE,'original','regular'),
('NED12','national_team','NED','A',12,'player','Netherlands Player 12',TRUE,'original','regular'),
('NED13','national_team','NED','A',13,'team_photo','Netherlands Team Photo',TRUE,'original','regular'),
('NED14','national_team','NED','A',14,'player','Netherlands Player 14',TRUE,'original','regular'),
('NED15','national_team','NED','A',15,'player','Netherlands Player 15',TRUE,'original','regular'),
('NED16','national_team','NED','A',16,'player','Netherlands Player 16',TRUE,'original','regular'),
('NED17','national_team','NED','A',17,'player','Netherlands Player 17',TRUE,'original','regular'),
('NED18','national_team','NED','A',18,'player','Netherlands Player 18',TRUE,'original','regular'),
('NED19','national_team','NED','A',19,'player','Netherlands Player 19',TRUE,'original','regular'),
('NED20','national_team','NED','A',20,'player','Netherlands Player 20',TRUE,'original','regular')
ON CONFLICT (natural_key) DO NOTHING;

-- GROUP B: England, Iran, USA, Wales
INSERT INTO stickers (natural_key, section_type, team_slug, group_code, position_in_section, position_role, sticker_name, is_official_album, release_batch, rarity) VALUES
('ENG1','national_team','ENG','B',1,'badge','England Badge',TRUE,'original','regular'),('ENG2','national_team','ENG','B',2,'player','England Player 2',TRUE,'original','regular'),('ENG3','national_team','ENG','B',3,'player','England Player 3',TRUE,'original','regular'),('ENG4','national_team','ENG','B',4,'player','England Player 4',TRUE,'original','regular'),('ENG5','national_team','ENG','B',5,'player','England Player 5',TRUE,'original','regular'),('ENG6','national_team','ENG','B',6,'player','England Player 6',TRUE,'original','regular'),('ENG7','national_team','ENG','B',7,'player','England Player 7',TRUE,'original','regular'),('ENG8','national_team','ENG','B',8,'player','England Player 8',TRUE,'original','regular'),('ENG9','national_team','ENG','B',9,'player','England Player 9',TRUE,'original','regular'),('ENG10','national_team','ENG','B',10,'player','England Player 10',TRUE,'original','regular'),('ENG11','national_team','ENG','B',11,'player','England Player 11',TRUE,'original','regular'),('ENG12','national_team','ENG','B',12,'player','England Player 12',TRUE,'original','regular'),('ENG13','national_team','ENG','B',13,'team_photo','England Team Photo',TRUE,'original','regular'),('ENG14','national_team','ENG','B',14,'player','England Player 14',TRUE,'original','regular'),('ENG15','national_team','ENG','B',15,'player','England Player 15',TRUE,'original','regular'),('ENG16','national_team','ENG','B',16,'player','England Player 16',TRUE,'original','regular'),('ENG17','national_team','ENG','B',17,'player','England Player 17',TRUE,'original','regular'),('ENG18','national_team','ENG','B',18,'player','England Player 18',TRUE,'original','regular'),('ENG19','national_team','ENG','B',19,'player','England Player 19',TRUE,'original','regular'),('ENG20','national_team','ENG','B',20,'player','England Player 20',TRUE,'original','regular'),
('IRN1','national_team','IRN','B',1,'badge','Iran Badge',TRUE,'original','regular'),('IRN2','national_team','IRN','B',2,'player','Iran Player 2',TRUE,'original','regular'),('IRN3','national_team','IRN','B',3,'player','Iran Player 3',TRUE,'original','regular'),('IRN4','national_team','IRN','B',4,'player','Iran Player 4',TRUE,'original','regular'),('IRN5','national_team','IRN','B',5,'player','Iran Player 5',TRUE,'original','regular'),('IRN6','national_team','IRN','B',6,'player','Iran Player 6',TRUE,'original','regular'),('IRN7','national_team','IRN','B',7,'player','Iran Player 7',TRUE,'original','regular'),('IRN8','national_team','IRN','B',8,'player','Iran Player 8',TRUE,'original','regular'),('IRN9','national_team','IRN','B',9,'player','Iran Player 9',TRUE,'original','regular'),('IRN10','national_team','IRN','B',10,'player','Iran Player 10',TRUE,'original','regular'),('IRN11','national_team','IRN','B',11,'player','Iran Player 11',TRUE,'original','regular'),('IRN12','national_team','IRN','B',12,'player','Iran Player 12',TRUE,'original','regular'),('IRN13','national_team','IRN','B',13,'team_photo','Iran Team Photo',TRUE,'original','regular'),('IRN14','national_team','IRN','B',14,'player','Iran Player 14',TRUE,'original','regular'),('IRN15','national_team','IRN','B',15,'player','Iran Player 15',TRUE,'original','regular'),('IRN16','national_team','IRN','B',16,'player','Iran Player 16',TRUE,'original','regular'),('IRN17','national_team','IRN','B',17,'player','Iran Player 17',TRUE,'original','regular'),('IRN18','national_team','IRN','B',18,'player','Iran Player 18',TRUE,'original','regular'),('IRN19','national_team','IRN','B',19,'player','Iran Player 19',TRUE,'original','regular'),('IRN20','national_team','IRN','B',20,'player','Iran Player 20',TRUE,'original','regular'),
('USA1','national_team','USA','B',1,'badge','USA Badge',TRUE,'original','regular'),('USA2','national_team','USA','B',2,'player','USA Player 2',TRUE,'original','regular'),('USA3','national_team','USA','B',3,'player','USA Player 3',TRUE,'original','regular'),('USA4','national_team','USA','B',4,'player','USA Player 4',TRUE,'original','regular'),('USA5','national_team','USA','B',5,'player','USA Player 5',TRUE,'original','regular'),('USA6','national_team','USA','B',6,'player','USA Player 6',TRUE,'original','regular'),('USA7','national_team','USA','B',7,'player','USA Player 7',TRUE,'original','regular'),('USA8','national_team','USA','B',8,'player','USA Player 8',TRUE,'original','regular'),('USA9','national_team','USA','B',9,'player','USA Player 9',TRUE,'original','regular'),('USA10','national_team','USA','B',10,'player','USA Player 10',TRUE,'original','regular'),('USA11','national_team','USA','B',11,'player','USA Player 11',TRUE,'original','regular'),('USA12','national_team','USA','B',12,'player','USA Player 12',TRUE,'original','regular'),('USA13','national_team','USA','B',13,'team_photo','USA Team Photo',TRUE,'original','regular'),('USA14','national_team','USA','B',14,'player','USA Player 14',TRUE,'original','regular'),('USA15','national_team','USA','B',15,'player','USA Player 15',TRUE,'original','regular'),('USA16','national_team','USA','B',16,'player','USA Player 16',TRUE,'original','regular'),('USA17','national_team','USA','B',17,'player','USA Player 17',TRUE,'original','regular'),('USA18','national_team','USA','B',18,'player','USA Player 18',TRUE,'original','regular'),('USA19','national_team','USA','B',19,'player','USA Player 19',TRUE,'original','regular'),('USA20','national_team','USA','B',20,'player','USA Player 20',TRUE,'original','regular'),
('WAL1','national_team','WAL','B',1,'badge','Wales Badge',TRUE,'original','regular'),('WAL2','national_team','WAL','B',2,'player','Wales Player 2',TRUE,'original','regular'),('WAL3','national_team','WAL','B',3,'player','Wales Player 3',TRUE,'original','regular'),('WAL4','national_team','WAL','B',4,'player','Wales Player 4',TRUE,'original','regular'),('WAL5','national_team','WAL','B',5,'player','Wales Player 5',TRUE,'original','regular'),('WAL6','national_team','WAL','B',6,'player','Wales Player 6',TRUE,'original','regular'),('WAL7','national_team','WAL','B',7,'player','Wales Player 7',TRUE,'original','regular'),('WAL8','national_team','WAL','B',8,'player','Wales Player 8',TRUE,'original','regular'),('WAL9','national_team','WAL','B',9,'player','Wales Player 9',TRUE,'original','regular'),('WAL10','national_team','WAL','B',10,'player','Wales Player 10',TRUE,'original','regular'),('WAL11','national_team','WAL','B',11,'player','Wales Player 11',TRUE,'original','regular'),('WAL12','national_team','WAL','B',12,'player','Wales Player 12',TRUE,'original','regular'),('WAL13','national_team','WAL','B',13,'team_photo','Wales Team Photo',TRUE,'original','regular'),('WAL14','national_team','WAL','B',14,'player','Wales Player 14',TRUE,'original','regular'),('WAL15','national_team','WAL','B',15,'player','Wales Player 15',TRUE,'original','regular'),('WAL16','national_team','WAL','B',16,'player','Wales Player 16',TRUE,'original','regular'),('WAL17','national_team','WAL','B',17,'player','Wales Player 17',TRUE,'original','regular'),('WAL18','national_team','WAL','B',18,'player','Wales Player 18',TRUE,'original','regular'),('WAL19','national_team','WAL','B',19,'player','Wales Player 19',TRUE,'original','regular'),('WAL20','national_team','WAL','B',20,'player','Wales Player 20',TRUE,'original','regular')
ON CONFLICT (natural_key) DO NOTHING;

-- GROUP C: Argentina, Saudi Arabia, Mexico, Poland
INSERT INTO stickers (natural_key, section_type, team_slug, group_code, position_in_section, position_role, sticker_name, is_official_album, release_batch, rarity) VALUES
('ARG1','national_team','ARG','C',1,'badge','Argentina Badge',TRUE,'original','regular'),('ARG2','national_team','ARG','C',2,'player','Argentina Player 2',TRUE,'original','regular'),('ARG3','national_team','ARG','C',3,'player','Argentina Player 3',TRUE,'original','regular'),('ARG4','national_team','ARG','C',4,'player','Argentina Player 4',TRUE,'original','regular'),('ARG5','national_team','ARG','C',5,'player','Argentina Player 5',TRUE,'original','regular'),('ARG6','national_team','ARG','C',6,'player','Argentina Player 6',TRUE,'original','regular'),('ARG7','national_team','ARG','C',7,'player','Argentina Player 7',TRUE,'original','regular'),('ARG8','national_team','ARG','C',8,'player','Argentina Player 8',TRUE,'original','regular'),('ARG9','national_team','ARG','C',9,'player','Argentina Player 9',TRUE,'original','regular'),('ARG10','national_team','ARG','C',10,'player','Argentina Player 10',TRUE,'original','regular'),('ARG11','national_team','ARG','C',11,'player','Argentina Player 11',TRUE,'original','regular'),('ARG12','national_team','ARG','C',12,'player','Argentina Player 12',TRUE,'original','regular'),('ARG13','national_team','ARG','C',13,'team_photo','Argentina Team Photo',TRUE,'original','regular'),('ARG14','national_team','ARG','C',14,'player','Argentina Player 14',TRUE,'original','regular'),('ARG15','national_team','ARG','C',15,'player','Argentina Player 15',TRUE,'original','regular'),('ARG16','national_team','ARG','C',16,'player','Argentina Player 16',TRUE,'original','regular'),('ARG17','national_team','ARG','C',17,'player','Argentina Player 17',TRUE,'original','regular'),('ARG18','national_team','ARG','C',18,'player','Argentina Player 18',TRUE,'original','regular'),('ARG19','national_team','ARG','C',19,'player','Argentina Player 19',TRUE,'original','regular'),('ARG20','national_team','ARG','C',20,'player','Argentina Player 20',TRUE,'original','regular'),
('KSA1','national_team','KSA','C',1,'badge','Saudi Arabia Badge',TRUE,'original','regular'),('KSA2','national_team','KSA','C',2,'player','Saudi Arabia Player 2',TRUE,'original','regular'),('KSA3','national_team','KSA','C',3,'player','Saudi Arabia Player 3',TRUE,'original','regular'),('KSA4','national_team','KSA','C',4,'player','Saudi Arabia Player 4',TRUE,'original','regular'),('KSA5','national_team','KSA','C',5,'player','Saudi Arabia Player 5',TRUE,'original','regular'),('KSA6','national_team','KSA','C',6,'player','Saudi Arabia Player 6',TRUE,'original','regular'),('KSA7','national_team','KSA','C',7,'player','Saudi Arabia Player 7',TRUE,'original','regular'),('KSA8','national_team','KSA','C',8,'player','Saudi Arabia Player 8',TRUE,'original','regular'),('KSA9','national_team','KSA','C',9,'player','Saudi Arabia Player 9',TRUE,'original','regular'),('KSA10','national_team','KSA','C',10,'player','Saudi Arabia Player 10',TRUE,'original','regular'),('KSA11','national_team','KSA','C',11,'player','Saudi Arabia Player 11',TRUE,'original','regular'),('KSA12','national_team','KSA','C',12,'player','Saudi Arabia Player 12',TRUE,'original','regular'),('KSA13','national_team','KSA','C',13,'team_photo','Saudi Arabia Team Photo',TRUE,'original','regular'),('KSA14','national_team','KSA','C',14,'player','Saudi Arabia Player 14',TRUE,'original','regular'),('KSA15','national_team','KSA','C',15,'player','Saudi Arabia Player 15',TRUE,'original','regular'),('KSA16','national_team','KSA','C',16,'player','Saudi Arabia Player 16',TRUE,'original','regular'),('KSA17','national_team','KSA','C',17,'player','Saudi Arabia Player 17',TRUE,'original','regular'),('KSA18','national_team','KSA','C',18,'player','Saudi Arabia Player 18',TRUE,'original','regular'),('KSA19','national_team','KSA','C',19,'player','Saudi Arabia Player 19',TRUE,'original','regular'),('KSA20','national_team','KSA','C',20,'player','Saudi Arabia Player 20',TRUE,'original','regular'),
('MEX1','national_team','MEX','C',1,'badge','Mexico Badge',TRUE,'original','regular'),('MEX2','national_team','MEX','C',2,'player','Mexico Player 2',TRUE,'original','regular'),('MEX3','national_team','MEX','C',3,'player','Mexico Player 3',TRUE,'original','regular'),('MEX4','national_team','MEX','C',4,'player','Mexico Player 4',TRUE,'original','regular'),('MEX5','national_team','MEX','C',5,'player','Mexico Player 5',TRUE,'original','regular'),('MEX6','national_team','MEX','C',6,'player','Mexico Player 6',TRUE,'original','regular'),('MEX7','national_team','MEX','C',7,'player','Mexico Player 7',TRUE,'original','regular'),('MEX8','national_team','MEX','C',8,'player','Mexico Player 8',TRUE,'original','regular'),('MEX9','national_team','MEX','C',9,'player','Mexico Player 9',TRUE,'original','regular'),('MEX10','national_team','MEX','C',10,'player','Mexico Player 10',TRUE,'original','regular'),('MEX11','national_team','MEX','C',11,'player','Mexico Player 11',TRUE,'original','regular'),('MEX12','national_team','MEX','C',12,'player','Mexico Player 12',TRUE,'original','regular'),('MEX13','national_team','MEX','C',13,'team_photo','Mexico Team Photo',TRUE,'original','regular'),('MEX14','national_team','MEX','C',14,'player','Mexico Player 14',TRUE,'original','regular'),('MEX15','national_team','MEX','C',15,'player','Mexico Player 15',TRUE,'original','regular'),('MEX16','national_team','MEX','C',16,'player','Mexico Player 16',TRUE,'original','regular'),('MEX17','national_team','MEX','C',17,'player','Mexico Player 17',TRUE,'original','regular'),('MEX18','national_team','MEX','C',18,'player','Mexico Player 18',TRUE,'original','regular'),('MEX19','national_team','MEX','C',19,'player','Mexico Player 19',TRUE,'original','regular'),('MEX20','national_team','MEX','C',20,'player','Mexico Player 20',TRUE,'original','regular'),
('POL1','national_team','POL','C',1,'badge','Poland Badge',TRUE,'original','regular'),('POL2','national_team','POL','C',2,'player','Poland Player 2',TRUE,'original','regular'),('POL3','national_team','POL','C',3,'player','Poland Player 3',TRUE,'original','regular'),('POL4','national_team','POL','C',4,'player','Poland Player 4',TRUE,'original','regular'),('POL5','national_team','POL','C',5,'player','Poland Player 5',TRUE,'original','regular'),('POL6','national_team','POL','C',6,'player','Poland Player 6',TRUE,'original','regular'),('POL7','national_team','POL','C',7,'player','Poland Player 7',TRUE,'original','regular'),('POL8','national_team','POL','C',8,'player','Poland Player 8',TRUE,'original','regular'),('POL9','national_team','POL','C',9,'player','Poland Player 9',TRUE,'original','regular'),('POL10','national_team','POL','C',10,'player','Poland Player 10',TRUE,'original','regular'),('POL11','national_team','POL','C',11,'player','Poland Player 11',TRUE,'original','regular'),('POL12','national_team','POL','C',12,'player','Poland Player 12',TRUE,'original','regular'),('POL13','national_team','POL','C',13,'team_photo','Poland Team Photo',TRUE,'original','regular'),('POL14','national_team','POL','C',14,'player','Poland Player 14',TRUE,'original','regular'),('POL15','national_team','POL','C',15,'player','Poland Player 15',TRUE,'original','regular'),('POL16','national_team','POL','C',16,'player','Poland Player 16',TRUE,'original','regular'),('POL17','national_team','POL','C',17,'player','Poland Player 17',TRUE,'original','regular'),('POL18','national_team','POL','C',18,'player','Poland Player 18',TRUE,'original','regular'),('POL19','national_team','POL','C',19,'player','Poland Player 19',TRUE,'original','regular'),('POL20','national_team','POL','C',20,'player','Poland Player 20',TRUE,'original','regular')
ON CONFLICT (natural_key) DO NOTHING;

-- GROUP D: France, Australia, Denmark, Tunisia
INSERT INTO stickers (natural_key, section_type, team_slug, group_code, position_in_section, position_role, sticker_name, is_official_album, release_batch, rarity) VALUES
('FRA1','national_team','FRA','D',1,'badge','France Badge',TRUE,'original','regular'),('FRA2','national_team','FRA','D',2,'player','France Player 2',TRUE,'original','regular'),('FRA3','national_team','FRA','D',3,'player','France Player 3',TRUE,'original','regular'),('FRA4','national_team','FRA','D',4,'player','France Player 4',TRUE,'original','regular'),('FRA5','national_team','FRA','D',5,'player','France Player 5',TRUE,'original','regular'),('FRA6','national_team','FRA','D',6,'player','France Player 6',TRUE,'original','regular'),('FRA7','national_team','FRA','D',7,'player','France Player 7',TRUE,'original','regular'),('FRA8','national_team','FRA','D',8,'player','France Player 8',TRUE,'original','regular'),('FRA9','national_team','FRA','D',9,'player','France Player 9',TRUE,'original','regular'),('FRA10','national_team','FRA','D',10,'player','France Player 10',TRUE,'original','regular'),('FRA11','national_team','FRA','D',11,'player','France Player 11',TRUE,'original','regular'),('FRA12','national_team','FRA','D',12,'player','France Player 12',TRUE,'original','regular'),('FRA13','national_team','FRA','D',13,'team_photo','France Team Photo',TRUE,'original','regular'),('FRA14','national_team','FRA','D',14,'player','France Player 14',TRUE,'original','regular'),('FRA15','national_team','FRA','D',15,'player','France Player 15',TRUE,'original','regular'),('FRA16','national_team','FRA','D',16,'player','France Player 16',TRUE,'original','regular'),('FRA17','national_team','FRA','D',17,'player','France Player 17',TRUE,'original','regular'),('FRA18','national_team','FRA','D',18,'player','France Player 18',TRUE,'original','regular'),('FRA19','national_team','FRA','D',19,'player','France Player 19',TRUE,'original','regular'),('FRA20','national_team','FRA','D',20,'player','France Player 20',TRUE,'original','regular'),
('AUS1','national_team','AUS','D',1,'badge','Australia Badge',TRUE,'original','regular'),('AUS2','national_team','AUS','D',2,'player','Australia Player 2',TRUE,'original','regular'),('AUS3','national_team','AUS','D',3,'player','Australia Player 3',TRUE,'original','regular'),('AUS4','national_team','AUS','D',4,'player','Australia Player 4',TRUE,'original','regular'),('AUS5','national_team','AUS','D',5,'player','Australia Player 5',TRUE,'original','regular'),('AUS6','national_team','AUS','D',6,'player','Australia Player 6',TRUE,'original','regular'),('AUS7','national_team','AUS','D',7,'player','Australia Player 7',TRUE,'original','regular'),('AUS8','national_team','AUS','D',8,'player','Australia Player 8',TRUE,'original','regular'),('AUS9','national_team','AUS','D',9,'player','Australia Player 9',TRUE,'original','regular'),('AUS10','national_team','AUS','D',10,'player','Australia Player 10',TRUE,'original','regular'),('AUS11','national_team','AUS','D',11,'player','Australia Player 11',TRUE,'original','regular'),('AUS12','national_team','AUS','D',12,'player','Australia Player 12',TRUE,'original','regular'),('AUS13','national_team','AUS','D',13,'team_photo','Australia Team Photo',TRUE,'original','regular'),('AUS14','national_team','AUS','D',14,'player','Australia Player 14',TRUE,'original','regular'),('AUS15','national_team','AUS','D',15,'player','Australia Player 15',TRUE,'original','regular'),('AUS16','national_team','AUS','D',16,'player','Australia Player 16',TRUE,'original','regular'),('AUS17','national_team','AUS','D',17,'player','Australia Player 17',TRUE,'original','regular'),('AUS18','national_team','AUS','D',18,'player','Australia Player 18',TRUE,'original','regular'),('AUS19','national_team','AUS','D',19,'player','Australia Player 19',TRUE,'original','regular'),('AUS20','national_team','AUS','D',20,'player','Australia Player 20',TRUE,'original','regular'),
('DEN1','national_team','DEN','D',1,'badge','Denmark Badge',TRUE,'original','regular'),('DEN2','national_team','DEN','D',2,'player','Denmark Player 2',TRUE,'original','regular'),('DEN3','national_team','DEN','D',3,'player','Denmark Player 3',TRUE,'original','regular'),('DEN4','national_team','DEN','D',4,'player','Denmark Player 4',TRUE,'original','regular'),('DEN5','national_team','DEN','D',5,'player','Denmark Player 5',TRUE,'original','regular'),('DEN6','national_team','DEN','D',6,'player','Denmark Player 6',TRUE,'original','regular'),('DEN7','national_team','DEN','D',7,'player','Denmark Player 7',TRUE,'original','regular'),('DEN8','national_team','DEN','D',8,'player','Denmark Player 8',TRUE,'original','regular'),('DEN9','national_team','DEN','D',9,'player','Denmark Player 9',TRUE,'original','regular'),('DEN10','national_team','DEN','D',10,'player','Denmark Player 10',TRUE,'original','regular'),('DEN11','national_team','DEN','D',11,'player','Denmark Player 11',TRUE,'original','regular'),('DEN12','national_team','DEN','D',12,'player','Denmark Player 12',TRUE,'original','regular'),('DEN13','national_team','DEN','D',13,'team_photo','Denmark Team Photo',TRUE,'original','regular'),('DEN14','national_team','DEN','D',14,'player','Denmark Player 14',TRUE,'original','regular'),('DEN15','national_team','DEN','D',15,'player','Denmark Player 15',TRUE,'original','regular'),('DEN16','national_team','DEN','D',16,'player','Denmark Player 16',TRUE,'original','regular'),('DEN17','national_team','DEN','D',17,'player','Denmark Player 17',TRUE,'original','regular'),('DEN18','national_team','DEN','D',18,'player','Denmark Player 18',TRUE,'original','regular'),('DEN19','national_team','DEN','D',19,'player','Denmark Player 19',TRUE,'original','regular'),('DEN20','national_team','DEN','D',20,'player','Denmark Player 20',TRUE,'original','regular'),
('TUN1','national_team','TUN','D',1,'badge','Tunisia Badge',TRUE,'original','regular'),('TUN2','national_team','TUN','D',2,'player','Tunisia Player 2',TRUE,'original','regular'),('TUN3','national_team','TUN','D',3,'player','Tunisia Player 3',TRUE,'original','regular'),('TUN4','national_team','TUN','D',4,'player','Tunisia Player 4',TRUE,'original','regular'),('TUN5','national_team','TUN','D',5,'player','Tunisia Player 5',TRUE,'original','regular'),('TUN6','national_team','TUN','D',6,'player','Tunisia Player 6',TRUE,'original','regular'),('TUN7','national_team','TUN','D',7,'player','Tunisia Player 7',TRUE,'original','regular'),('TUN8','national_team','TUN','D',8,'player','Tunisia Player 8',TRUE,'original','regular'),('TUN9','national_team','TUN','D',9,'player','Tunisia Player 9',TRUE,'original','regular'),('TUN10','national_team','TUN','D',10,'player','Tunisia Player 10',TRUE,'original','regular'),('TUN11','national_team','TUN','D',11,'player','Tunisia Player 11',TRUE,'original','regular'),('TUN12','national_team','TUN','D',12,'player','Tunisia Player 12',TRUE,'original','regular'),('TUN13','national_team','TUN','D',13,'team_photo','Tunisia Team Photo',TRUE,'original','regular'),('TUN14','national_team','TUN','D',14,'player','Tunisia Player 14',TRUE,'original','regular'),('TUN15','national_team','TUN','D',15,'player','Tunisia Player 15',TRUE,'original','regular'),('TUN16','national_team','TUN','D',16,'player','Tunisia Player 16',TRUE,'original','regular'),('TUN17','national_team','TUN','D',17,'player','Tunisia Player 17',TRUE,'original','regular'),('TUN18','national_team','TUN','D',18,'player','Tunisia Player 18',TRUE,'original','regular'),('TUN19','national_team','TUN','D',19,'player','Tunisia Player 19',TRUE,'original','regular'),('TUN20','national_team','TUN','D',20,'player','Tunisia Player 20',TRUE,'original','regular')
ON CONFLICT (natural_key) DO NOTHING;

-- GROUP E: Spain, Costa Rica, Germany, Japan
INSERT INTO stickers (natural_key, section_type, team_slug, group_code, position_in_section, position_role, sticker_name, is_official_album, release_batch, rarity) VALUES
('ESP1','national_team','ESP','E',1,'badge','Spain Badge',TRUE,'original','regular'),('ESP2','national_team','ESP','E',2,'player','Spain Player 2',TRUE,'original','regular'),('ESP3','national_team','ESP','E',3,'player','Spain Player 3',TRUE,'original','regular'),('ESP4','national_team','ESP','E',4,'player','Spain Player 4',TRUE,'original','regular'),('ESP5','national_team','ESP','E',5,'player','Spain Player 5',TRUE,'original','regular'),('ESP6','national_team','ESP','E',6,'player','Spain Player 6',TRUE,'original','regular'),('ESP7','national_team','ESP','E',7,'player','Spain Player 7',TRUE,'original','regular'),('ESP8','national_team','ESP','E',8,'player','Spain Player 8',TRUE,'original','regular'),('ESP9','national_team','ESP','E',9,'player','Spain Player 9',TRUE,'original','regular'),('ESP10','national_team','ESP','E',10,'player','Spain Player 10',TRUE,'original','regular'),('ESP11','national_team','ESP','E',11,'player','Spain Player 11',TRUE,'original','regular'),('ESP12','national_team','ESP','E',12,'player','Spain Player 12',TRUE,'original','regular'),('ESP13','national_team','ESP','E',13,'team_photo','Spain Team Photo',TRUE,'original','regular'),('ESP14','national_team','ESP','E',14,'player','Spain Player 14',TRUE,'original','regular'),('ESP15','national_team','ESP','E',15,'player','Spain Player 15',TRUE,'original','regular'),('ESP16','national_team','ESP','E',16,'player','Spain Player 16',TRUE,'original','regular'),('ESP17','national_team','ESP','E',17,'player','Spain Player 17',TRUE,'original','regular'),('ESP18','national_team','ESP','E',18,'player','Spain Player 18',TRUE,'original','regular'),('ESP19','national_team','ESP','E',19,'player','Spain Player 19',TRUE,'original','regular'),('ESP20','national_team','ESP','E',20,'player','Spain Player 20',TRUE,'original','regular'),
('CRC1','national_team','CRC','E',1,'badge','Costa Rica Badge',TRUE,'original','regular'),('CRC2','national_team','CRC','E',2,'player','Costa Rica Player 2',TRUE,'original','regular'),('CRC3','national_team','CRC','E',3,'player','Costa Rica Player 3',TRUE,'original','regular'),('CRC4','national_team','CRC','E',4,'player','Costa Rica Player 4',TRUE,'original','regular'),('CRC5','national_team','CRC','E',5,'player','Costa Rica Player 5',TRUE,'original','regular'),('CRC6','national_team','CRC','E',6,'player','Costa Rica Player 6',TRUE,'original','regular'),('CRC7','national_team','CRC','E',7,'player','Costa Rica Player 7',TRUE,'original','regular'),('CRC8','national_team','CRC','E',8,'player','Costa Rica Player 8',TRUE,'original','regular'),('CRC9','national_team','CRC','E',9,'player','Costa Rica Player 9',TRUE,'original','regular'),('CRC10','national_team','CRC','E',10,'player','Costa Rica Player 10',TRUE,'original','regular'),('CRC11','national_team','CRC','E',11,'player','Costa Rica Player 11',TRUE,'original','regular'),('CRC12','national_team','CRC','E',12,'player','Costa Rica Player 12',TRUE,'original','regular'),('CRC13','national_team','CRC','E',13,'team_photo','Costa Rica Team Photo',TRUE,'original','regular'),('CRC14','national_team','CRC','E',14,'player','Costa Rica Player 14',TRUE,'original','regular'),('CRC15','national_team','CRC','E',15,'player','Costa Rica Player 15',TRUE,'original','regular'),('CRC16','national_team','CRC','E',16,'player','Costa Rica Player 16',TRUE,'original','regular'),('CRC17','national_team','CRC','E',17,'player','Costa Rica Player 17',TRUE,'original','regular'),('CRC18','national_team','CRC','E',18,'player','Costa Rica Player 18',TRUE,'original','regular'),('CRC19','national_team','CRC','E',19,'player','Costa Rica Player 19',TRUE,'original','regular'),('CRC20','national_team','CRC','E',20,'player','Costa Rica Player 20',TRUE,'original','regular'),
('GER1','national_team','GER','E',1,'badge','Germany Badge',TRUE,'original','regular'),('GER2','national_team','GER','E',2,'player','Germany Player 2',TRUE,'original','regular'),('GER3','national_team','GER','E',3,'player','Germany Player 3',TRUE,'original','regular'),('GER4','national_team','GER','E',4,'player','Germany Player 4',TRUE,'original','regular'),('GER5','national_team','GER','E',5,'player','Germany Player 5',TRUE,'original','regular'),('GER6','national_team','GER','E',6,'player','Germany Player 6',TRUE,'original','regular'),('GER7','national_team','GER','E',7,'player','Germany Player 7',TRUE,'original','regular'),('GER8','national_team','GER','E',8,'player','Germany Player 8',TRUE,'original','regular'),('GER9','national_team','GER','E',9,'player','Germany Player 9',TRUE,'original','regular'),('GER10','national_team','GER','E',10,'player','Germany Player 10',TRUE,'original','regular'),('GER11','national_team','GER','E',11,'player','Germany Player 11',TRUE,'original','regular'),('GER12','national_team','GER','E',12,'player','Germany Player 12',TRUE,'original','regular'),('GER13','national_team','GER','E',13,'team_photo','Germany Team Photo',TRUE,'original','regular'),('GER14','national_team','GER','E',14,'player','Germany Player 14',TRUE,'original','regular'),('GER15','national_team','GER','E',15,'player','Germany Player 15',TRUE,'original','regular'),('GER16','national_team','GER','E',16,'player','Germany Player 16',TRUE,'original','regular'),('GER17','national_team','GER','E',17,'player','Germany Player 17',TRUE,'original','regular'),('GER18','national_team','GER','E',18,'player','Germany Player 18',TRUE,'original','regular'),('GER19','national_team','GER','E',19,'player','Germany Player 19',TRUE,'original','regular'),('GER20','national_team','GER','E',20,'player','Germany Player 20',TRUE,'original','regular'),
('JPN1','national_team','JPN','E',1,'badge','Japan Badge',TRUE,'original','regular'),('JPN2','national_team','JPN','E',2,'player','Japan Player 2',TRUE,'original','regular'),('JPN3','national_team','JPN','E',3,'player','Japan Player 3',TRUE,'original','regular'),('JPN4','national_team','JPN','E',4,'player','Japan Player 4',TRUE,'original','regular'),('JPN5','national_team','JPN','E',5,'player','Japan Player 5',TRUE,'original','regular'),('JPN6','national_team','JPN','E',6,'player','Japan Player 6',TRUE,'original','regular'),('JPN7','national_team','JPN','E',7,'player','Japan Player 7',TRUE,'original','regular'),('JPN8','national_team','JPN','E',8,'player','Japan Player 8',TRUE,'original','regular'),('JPN9','national_team','JPN','E',9,'player','Japan Player 9',TRUE,'original','regular'),('JPN10','national_team','JPN','E',10,'player','Japan Player 10',TRUE,'original','regular'),('JPN11','national_team','JPN','E',11,'player','Japan Player 11',TRUE,'original','regular'),('JPN12','national_team','JPN','E',12,'player','Japan Player 12',TRUE,'original','regular'),('JPN13','national_team','JPN','E',13,'team_photo','Japan Team Photo',TRUE,'original','regular'),('JPN14','national_team','JPN','E',14,'player','Japan Player 14',TRUE,'original','regular'),('JPN15','national_team','JPN','E',15,'player','Japan Player 15',TRUE,'original','regular'),('JPN16','national_team','JPN','E',16,'player','Japan Player 16',TRUE,'original','regular'),('JPN17','national_team','JPN','E',17,'player','Japan Player 17',TRUE,'original','regular'),('JPN18','national_team','JPN','E',18,'player','Japan Player 18',TRUE,'original','regular'),('JPN19','national_team','JPN','E',19,'player','Japan Player 19',TRUE,'original','regular'),('JPN20','national_team','JPN','E',20,'player','Japan Player 20',TRUE,'original','regular')
ON CONFLICT (natural_key) DO NOTHING;

-- GROUP F: Belgium, Canada, Morocco, Croatia
INSERT INTO stickers (natural_key, section_type, team_slug, group_code, position_in_section, position_role, sticker_name, is_official_album, release_batch, rarity) VALUES
('BEL1','national_team','BEL','F',1,'badge','Belgium Badge',TRUE,'original','regular'),('BEL2','national_team','BEL','F',2,'player','Belgium Player 2',TRUE,'original','regular'),('BEL3','national_team','BEL','F',3,'player','Belgium Player 3',TRUE,'original','regular'),('BEL4','national_team','BEL','F',4,'player','Belgium Player 4',TRUE,'original','regular'),('BEL5','national_team','BEL','F',5,'player','Belgium Player 5',TRUE,'original','regular'),('BEL6','national_team','BEL','F',6,'player','Belgium Player 6',TRUE,'original','regular'),('BEL7','national_team','BEL','F',7,'player','Belgium Player 7',TRUE,'original','regular'),('BEL8','national_team','BEL','F',8,'player','Belgium Player 8',TRUE,'original','regular'),('BEL9','national_team','BEL','F',9,'player','Belgium Player 9',TRUE,'original','regular'),('BEL10','national_team','BEL','F',10,'player','Belgium Player 10',TRUE,'original','regular'),('BEL11','national_team','BEL','F',11,'player','Belgium Player 11',TRUE,'original','regular'),('BEL12','national_team','BEL','F',12,'player','Belgium Player 12',TRUE,'original','regular'),('BEL13','national_team','BEL','F',13,'team_photo','Belgium Team Photo',TRUE,'original','regular'),('BEL14','national_team','BEL','F',14,'player','Belgium Player 14',TRUE,'original','regular'),('BEL15','national_team','BEL','F',15,'player','Belgium Player 15',TRUE,'original','regular'),('BEL16','national_team','BEL','F',16,'player','Belgium Player 16',TRUE,'original','regular'),('BEL17','national_team','BEL','F',17,'player','Belgium Player 17',TRUE,'original','regular'),('BEL18','national_team','BEL','F',18,'player','Belgium Player 18',TRUE,'original','regular'),('BEL19','national_team','BEL','F',19,'player','Belgium Player 19',TRUE,'original','regular'),('BEL20','national_team','BEL','F',20,'player','Belgium Player 20',TRUE,'original','regular'),
('CAN1','national_team','CAN','F',1,'badge','Canada Badge',TRUE,'original','regular'),('CAN2','national_team','CAN','F',2,'player','Canada Player 2',TRUE,'original','regular'),('CAN3','national_team','CAN','F',3,'player','Canada Player 3',TRUE,'original','regular'),('CAN4','national_team','CAN','F',4,'player','Canada Player 4',TRUE,'original','regular'),('CAN5','national_team','CAN','F',5,'player','Canada Player 5',TRUE,'original','regular'),('CAN6','national_team','CAN','F',6,'player','Canada Player 6',TRUE,'original','regular'),('CAN7','national_team','CAN','F',7,'player','Canada Player 7',TRUE,'original','regular'),('CAN8','national_team','CAN','F',8,'player','Canada Player 8',TRUE,'original','regular'),('CAN9','national_team','CAN','F',9,'player','Canada Player 9',TRUE,'original','regular'),('CAN10','national_team','CAN','F',10,'player','Canada Player 10',TRUE,'original','regular'),('CAN11','national_team','CAN','F',11,'player','Canada Player 11',TRUE,'original','regular'),('CAN12','national_team','CAN','F',12,'player','Canada Player 12',TRUE,'original','regular'),('CAN13','national_team','CAN','F',13,'team_photo','Canada Team Photo',TRUE,'original','regular'),('CAN14','national_team','CAN','F',14,'player','Canada Player 14',TRUE,'original','regular'),('CAN15','national_team','CAN','F',15,'player','Canada Player 15',TRUE,'original','regular'),('CAN16','national_team','CAN','F',16,'player','Canada Player 16',TRUE,'original','regular'),('CAN17','national_team','CAN','F',17,'player','Canada Player 17',TRUE,'original','regular'),('CAN18','national_team','CAN','F',18,'player','Canada Player 18',TRUE,'original','regular'),('CAN19','national_team','CAN','F',19,'player','Canada Player 19',TRUE,'original','regular'),('CAN20','national_team','CAN','F',20,'player','Canada Player 20',TRUE,'original','regular'),
('MAR1','national_team','MAR','F',1,'badge','Morocco Badge',TRUE,'original','regular'),('MAR2','national_team','MAR','F',2,'player','Morocco Player 2',TRUE,'original','regular'),('MAR3','national_team','MAR','F',3,'player','Morocco Player 3',TRUE,'original','regular'),('MAR4','national_team','MAR','F',4,'player','Morocco Player 4',TRUE,'original','regular'),('MAR5','national_team','MAR','F',5,'player','Morocco Player 5',TRUE,'original','regular'),('MAR6','national_team','MAR','F',6,'player','Morocco Player 6',TRUE,'original','regular'),('MAR7','national_team','MAR','F',7,'player','Morocco Player 7',TRUE,'original','regular'),('MAR8','national_team','MAR','F',8,'player','Morocco Player 8',TRUE,'original','regular'),('MAR9','national_team','MAR','F',9,'player','Morocco Player 9',TRUE,'original','regular'),('MAR10','national_team','MAR','F',10,'player','Morocco Player 10',TRUE,'original','regular'),('MAR11','national_team','MAR','F',11,'player','Morocco Player 11',TRUE,'original','regular'),('MAR12','national_team','MAR','F',12,'player','Morocco Player 12',TRUE,'original','regular'),('MAR13','national_team','MAR','F',13,'team_photo','Morocco Team Photo',TRUE,'original','regular'),('MAR14','national_team','MAR','F',14,'player','Morocco Player 14',TRUE,'original','regular'),('MAR15','national_team','MAR','F',15,'player','Morocco Player 15',TRUE,'original','regular'),('MAR16','national_team','MAR','F',16,'player','Morocco Player 16',TRUE,'original','regular'),('MAR17','national_team','MAR','F',17,'player','Morocco Player 17',TRUE,'original','regular'),('MAR18','national_team','MAR','F',18,'player','Morocco Player 18',TRUE,'original','regular'),('MAR19','national_team','MAR','F',19,'player','Morocco Player 19',TRUE,'original','regular'),('MAR20','national_team','MAR','F',20,'player','Morocco Player 20',TRUE,'original','regular'),
('CRO1','national_team','CRO','F',1,'badge','Croatia Badge',TRUE,'original','regular'),('CRO2','national_team','CRO','F',2,'player','Croatia Player 2',TRUE,'original','regular'),('CRO3','national_team','CRO','F',3,'player','Croatia Player 3',TRUE,'original','regular'),('CRO4','national_team','CRO','F',4,'player','Croatia Player 4',TRUE,'original','regular'),('CRO5','national_team','CRO','F',5,'player','Croatia Player 5',TRUE,'original','regular'),('CRO6','national_team','CRO','F',6,'player','Croatia Player 6',TRUE,'original','regular'),('CRO7','national_team','CRO','F',7,'player','Croatia Player 7',TRUE,'original','regular'),('CRO8','national_team','CRO','F',8,'player','Croatia Player 8',TRUE,'original','regular'),('CRO9','national_team','CRO','F',9,'player','Croatia Player 9',TRUE,'original','regular'),('CRO10','national_team','CRO','F',10,'player','Croatia Player 10',TRUE,'original','regular'),('CRO11','national_team','CRO','F',11,'player','Croatia Player 11',TRUE,'original','regular'),('CRO12','national_team','CRO','F',12,'player','Croatia Player 12',TRUE,'original','regular'),('CRO13','national_team','CRO','F',13,'team_photo','Croatia Team Photo',TRUE,'original','regular'),('CRO14','national_team','CRO','F',14,'player','Croatia Player 14',TRUE,'original','regular'),('CRO15','national_team','CRO','F',15,'player','Croatia Player 15',TRUE,'original','regular'),('CRO16','national_team','CRO','F',16,'player','Croatia Player 16',TRUE,'original','regular'),('CRO17','national_team','CRO','F',17,'player','Croatia Player 17',TRUE,'original','regular'),('CRO18','national_team','CRO','F',18,'player','Croatia Player 18',TRUE,'original','regular'),('CRO19','national_team','CRO','F',19,'player','Croatia Player 19',TRUE,'original','regular'),('CRO20','national_team','CRO','F',20,'player','Croatia Player 20',TRUE,'original','regular')
ON CONFLICT (natural_key) DO NOTHING;

-- GROUP G: Brazil, Serbia, Switzerland, Cameroon
INSERT INTO stickers (natural_key, section_type, team_slug, group_code, position_in_section, position_role, sticker_name, is_official_album, release_batch, rarity) VALUES
('BRA1','national_team','BRA','G',1,'badge','Brazil Badge',TRUE,'original','regular'),('BRA2','national_team','BRA','G',2,'player','Brazil Player 2',TRUE,'original','regular'),('BRA3','national_team','BRA','G',3,'player','Brazil Player 3',TRUE,'original','regular'),('BRA4','national_team','BRA','G',4,'player','Brazil Player 4',TRUE,'original','regular'),('BRA5','national_team','BRA','G',5,'player','Brazil Player 5',TRUE,'original','regular'),('BRA6','national_team','BRA','G',6,'player','Brazil Player 6',TRUE,'original','regular'),('BRA7','national_team','BRA','G',7,'player','Brazil Player 7',TRUE,'original','regular'),('BRA8','national_team','BRA','G',8,'player','Brazil Player 8',TRUE,'original','regular'),('BRA9','national_team','BRA','G',9,'player','Brazil Player 9',TRUE,'original','regular'),('BRA10','national_team','BRA','G',10,'player','Brazil Player 10',TRUE,'original','regular'),('BRA11','national_team','BRA','G',11,'player','Brazil Player 11',TRUE,'original','regular'),('BRA12','national_team','BRA','G',12,'player','Brazil Player 12',TRUE,'original','regular'),('BRA13','national_team','BRA','G',13,'team_photo','Brazil Team Photo',TRUE,'original','regular'),('BRA14','national_team','BRA','G',14,'player','Brazil Player 14',TRUE,'original','regular'),('BRA15','national_team','BRA','G',15,'player','Brazil Player 15',TRUE,'original','regular'),('BRA16','national_team','BRA','G',16,'player','Brazil Player 16',TRUE,'original','regular'),('BRA17','national_team','BRA','G',17,'player','Brazil Player 17',TRUE,'original','regular'),('BRA18','national_team','BRA','G',18,'player','Brazil Player 18',TRUE,'original','regular'),('BRA19','national_team','BRA','G',19,'player','Brazil Player 19',TRUE,'original','regular'),('BRA20','national_team','BRA','G',20,'player','Brazil Player 20',TRUE,'original','regular'),
('SRB1','national_team','SRB','G',1,'badge','Serbia Badge',TRUE,'original','regular'),('SRB2','national_team','SRB','G',2,'player','Serbia Player 2',TRUE,'original','regular'),('SRB3','national_team','SRB','G',3,'player','Serbia Player 3',TRUE,'original','regular'),('SRB4','national_team','SRB','G',4,'player','Serbia Player 4',TRUE,'original','regular'),('SRB5','national_team','SRB','G',5,'player','Serbia Player 5',TRUE,'original','regular'),('SRB6','national_team','SRB','G',6,'player','Serbia Player 6',TRUE,'original','regular'),('SRB7','national_team','SRB','G',7,'player','Serbia Player 7',TRUE,'original','regular'),('SRB8','national_team','SRB','G',8,'player','Serbia Player 8',TRUE,'original','regular'),('SRB9','national_team','SRB','G',9,'player','Serbia Player 9',TRUE,'original','regular'),('SRB10','national_team','SRB','G',10,'player','Serbia Player 10',TRUE,'original','regular'),('SRB11','national_team','SRB','G',11,'player','Serbia Player 11',TRUE,'original','regular'),('SRB12','national_team','SRB','G',12,'player','Serbia Player 12',TRUE,'original','regular'),('SRB13','national_team','SRB','G',13,'team_photo','Serbia Team Photo',TRUE,'original','regular'),('SRB14','national_team','SRB','G',14,'player','Serbia Player 14',TRUE,'original','regular'),('SRB15','national_team','SRB','G',15,'player','Serbia Player 15',TRUE,'original','regular'),('SRB16','national_team','SRB','G',16,'player','Serbia Player 16',TRUE,'original','regular'),('SRB17','national_team','SRB','G',17,'player','Serbia Player 17',TRUE,'original','regular'),('SRB18','national_team','SRB','G',18,'player','Serbia Player 18',TRUE,'original','regular'),('SRB19','national_team','SRB','G',19,'player','Serbia Player 19',TRUE,'original','regular'),('SRB20','national_team','SRB','G',20,'player','Serbia Player 20',TRUE,'original','regular'),
('SUI1','national_team','SUI','G',1,'badge','Switzerland Badge',TRUE,'original','regular'),('SUI2','national_team','SUI','G',2,'player','Switzerland Player 2',TRUE,'original','regular'),('SUI3','national_team','SUI','G',3,'player','Switzerland Player 3',TRUE,'original','regular'),('SUI4','national_team','SUI','G',4,'player','Switzerland Player 4',TRUE,'original','regular'),('SUI5','national_team','SUI','G',5,'player','Switzerland Player 5',TRUE,'original','regular'),('SUI6','national_team','SUI','G',6,'player','Switzerland Player 6',TRUE,'original','regular'),('SUI7','national_team','SUI','G',7,'player','Switzerland Player 7',TRUE,'original','regular'),('SUI8','national_team','SUI','G',8,'player','Switzerland Player 8',TRUE,'original','regular'),('SUI9','national_team','SUI','G',9,'player','Switzerland Player 9',TRUE,'original','regular'),('SUI10','national_team','SUI','G',10,'player','Switzerland Player 10',TRUE,'original','regular'),('SUI11','national_team','SUI','G',11,'player','Switzerland Player 11',TRUE,'original','regular'),('SUI12','national_team','SUI','G',12,'player','Switzerland Player 12',TRUE,'original','regular'),('SUI13','national_team','SUI','G',13,'team_photo','Switzerland Team Photo',TRUE,'original','regular'),('SUI14','national_team','SUI','G',14,'player','Switzerland Player 14',TRUE,'original','regular'),('SUI15','national_team','SUI','G',15,'player','Switzerland Player 15',TRUE,'original','regular'),('SUI16','national_team','SUI','G',16,'player','Switzerland Player 16',TRUE,'original','regular'),('SUI17','national_team','SUI','G',17,'player','Switzerland Player 17',TRUE,'original','regular'),('SUI18','national_team','SUI','G',18,'player','Switzerland Player 18',TRUE,'original','regular'),('SUI19','national_team','SUI','G',19,'player','Switzerland Player 19',TRUE,'original','regular'),('SUI20','national_team','SUI','G',20,'player','Switzerland Player 20',TRUE,'original','regular'),
('CMR1','national_team','CMR','G',1,'badge','Cameroon Badge',TRUE,'original','regular'),('CMR2','national_team','CMR','G',2,'player','Cameroon Player 2',TRUE,'original','regular'),('CMR3','national_team','CMR','G',3,'player','Cameroon Player 3',TRUE,'original','regular'),('CMR4','national_team','CMR','G',4,'player','Cameroon Player 4',TRUE,'original','regular'),('CMR5','national_team','CMR','G',5,'player','Cameroon Player 5',TRUE,'original','regular'),('CMR6','national_team','CMR','G',6,'player','Cameroon Player 6',TRUE,'original','regular'),('CMR7','national_team','CMR','G',7,'player','Cameroon Player 7',TRUE,'original','regular'),('CMR8','national_team','CMR','G',8,'player','Cameroon Player 8',TRUE,'original','regular'),('CMR9','national_team','CMR','G',9,'player','Cameroon Player 9',TRUE,'original','regular'),('CMR10','national_team','CMR','G',10,'player','Cameroon Player 10',TRUE,'original','regular'),('CMR11','national_team','CMR','G',11,'player','Cameroon Player 11',TRUE,'original','regular'),('CMR12','national_team','CMR','G',12,'player','Cameroon Player 12',TRUE,'original','regular'),('CMR13','national_team','CMR','G',13,'team_photo','Cameroon Team Photo',TRUE,'original','regular'),('CMR14','national_team','CMR','G',14,'player','Cameroon Player 14',TRUE,'original','regular'),('CMR15','national_team','CMR','G',15,'player','Cameroon Player 15',TRUE,'original','regular'),('CMR16','national_team','CMR','G',16,'player','Cameroon Player 16',TRUE,'original','regular'),('CMR17','national_team','CMR','G',17,'player','Cameroon Player 17',TRUE,'original','regular'),('CMR18','national_team','CMR','G',18,'player','Cameroon Player 18',TRUE,'original','regular'),('CMR19','national_team','CMR','G',19,'player','Cameroon Player 19',TRUE,'original','regular'),('CMR20','national_team','CMR','G',20,'player','Cameroon Player 20',TRUE,'original','regular')
ON CONFLICT (natural_key) DO NOTHING;

-- GROUP H: Portugal, Ghana, Uruguay, South Korea
INSERT INTO stickers (natural_key, section_type, team_slug, group_code, position_in_section, position_role, sticker_name, is_official_album, release_batch, rarity) VALUES
('POR1','national_team','POR','H',1,'badge','Portugal Badge',TRUE,'original','regular'),('POR2','national_team','POR','H',2,'player','Portugal Player 2',TRUE,'original','regular'),('POR3','national_team','POR','H',3,'player','Portugal Player 3',TRUE,'original','regular'),('POR4','national_team','POR','H',4,'player','Portugal Player 4',TRUE,'original','regular'),('POR5','national_team','POR','H',5,'player','Portugal Player 5',TRUE,'original','regular'),('POR6','national_team','POR','H',6,'player','Portugal Player 6',TRUE,'original','regular'),('POR7','national_team','POR','H',7,'player','Portugal Player 7',TRUE,'original','regular'),('POR8','national_team','POR','H',8,'player','Portugal Player 8',TRUE,'original','regular'),('POR9','national_team','POR','H',9,'player','Portugal Player 9',TRUE,'original','regular'),('POR10','national_team','POR','H',10,'player','Portugal Player 10',TRUE,'original','regular'),('POR11','national_team','POR','H',11,'player','Portugal Player 11',TRUE,'original','regular'),('POR12','national_team','POR','H',12,'player','Portugal Player 12',TRUE,'original','regular'),('POR13','national_team','POR','H',13,'team_photo','Portugal Team Photo',TRUE,'original','regular'),('POR14','national_team','POR','H',14,'player','Portugal Player 14',TRUE,'original','regular'),('POR15','national_team','POR','H',15,'player','Portugal Player 15',TRUE,'original','regular'),('POR16','national_team','POR','H',16,'player','Portugal Player 16',TRUE,'original','regular'),('POR17','national_team','POR','H',17,'player','Portugal Player 17',TRUE,'original','regular'),('POR18','national_team','POR','H',18,'player','Portugal Player 18',TRUE,'original','regular'),('POR19','national_team','POR','H',19,'player','Portugal Player 19',TRUE,'original','regular'),('POR20','national_team','POR','H',20,'player','Portugal Player 20',TRUE,'original','regular'),
('GHA1','national_team','GHA','H',1,'badge','Ghana Badge',TRUE,'original','regular'),('GHA2','national_team','GHA','H',2,'player','Ghana Player 2',TRUE,'original','regular'),('GHA3','national_team','GHA','H',3,'player','Ghana Player 3',TRUE,'original','regular'),('GHA4','national_team','GHA','H',4,'player','Ghana Player 4',TRUE,'original','regular'),('GHA5','national_team','GHA','H',5,'player','Ghana Player 5',TRUE,'original','regular'),('GHA6','national_team','GHA','H',6,'player','Ghana Player 6',TRUE,'original','regular'),('GHA7','national_team','GHA','H',7,'player','Ghana Player 7',TRUE,'original','regular'),('GHA8','national_team','GHA','H',8,'player','Ghana Player 8',TRUE,'original','regular'),('GHA9','national_team','GHA','H',9,'player','Ghana Player 9',TRUE,'original','regular'),('GHA10','national_team','GHA','H',10,'player','Ghana Player 10',TRUE,'original','regular'),('GHA11','national_team','GHA','H',11,'player','Ghana Player 11',TRUE,'original','regular'),('GHA12','national_team','GHA','H',12,'player','Ghana Player 12',TRUE,'original','regular'),('GHA13','national_team','GHA','H',13,'team_photo','Ghana Team Photo',TRUE,'original','regular'),('GHA14','national_team','GHA','H',14,'player','Ghana Player 14',TRUE,'original','regular'),('GHA15','national_team','GHA','H',15,'player','Ghana Player 15',TRUE,'original','regular'),('GHA16','national_team','GHA','H',16,'player','Ghana Player 16',TRUE,'original','regular'),('GHA17','national_team','GHA','H',17,'player','Ghana Player 17',TRUE,'original','regular'),('GHA18','national_team','GHA','H',18,'player','Ghana Player 18',TRUE,'original','regular'),('GHA19','national_team','GHA','H',19,'player','Ghana Player 19',TRUE,'original','regular'),('GHA20','national_team','GHA','H',20,'player','Ghana Player 20',TRUE,'original','regular'),
('URU1','national_team','URU','H',1,'badge','Uruguay Badge',TRUE,'original','regular'),('URU2','national_team','URU','H',2,'player','Uruguay Player 2',TRUE,'original','regular'),('URU3','national_team','URU','H',3,'player','Uruguay Player 3',TRUE,'original','regular'),('URU4','national_team','URU','H',4,'player','Uruguay Player 4',TRUE,'original','regular'),('URU5','national_team','URU','H',5,'player','Uruguay Player 5',TRUE,'original','regular'),('URU6','national_team','URU','H',6,'player','Uruguay Player 6',TRUE,'original','regular'),('URU7','national_team','URU','H',7,'player','Uruguay Player 7',TRUE,'original','regular'),('URU8','national_team','URU','H',8,'player','Uruguay Player 8',TRUE,'original','regular'),('URU9','national_team','URU','H',9,'player','Uruguay Player 9',TRUE,'original','regular'),('URU10','national_team','URU','H',10,'player','Uruguay Player 10',TRUE,'original','regular'),('URU11','national_team','URU','H',11,'player','Uruguay Player 11',TRUE,'original','regular'),('URU12','national_team','URU','H',12,'player','Uruguay Player 12',TRUE,'original','regular'),('URU13','national_team','URU','H',13,'team_photo','Uruguay Team Photo',TRUE,'original','regular'),('URU14','national_team','URU','H',14,'player','Uruguay Player 14',TRUE,'original','regular'),('URU15','national_team','URU','H',15,'player','Uruguay Player 15',TRUE,'original','regular'),('URU16','national_team','URU','H',16,'player','Uruguay Player 16',TRUE,'original','regular'),('URU17','national_team','URU','H',17,'player','Uruguay Player 17',TRUE,'original','regular'),('URU18','national_team','URU','H',18,'player','Uruguay Player 18',TRUE,'original','regular'),('URU19','national_team','URU','H',19,'player','Uruguay Player 19',TRUE,'original','regular'),('URU20','national_team','URU','H',20,'player','Uruguay Player 20',TRUE,'original','regular'),
('KOR1','national_team','KOR','H',1,'badge','South Korea Badge',TRUE,'original','regular'),('KOR2','national_team','KOR','H',2,'player','South Korea Player 2',TRUE,'original','regular'),('KOR3','national_team','KOR','H',3,'player','South Korea Player 3',TRUE,'original','regular'),('KOR4','national_team','KOR','H',4,'player','South Korea Player 4',TRUE,'original','regular'),('KOR5','national_team','KOR','H',5,'player','South Korea Player 5',TRUE,'original','regular'),('KOR6','national_team','KOR','H',6,'player','South Korea Player 6',TRUE,'original','regular'),('KOR7','national_team','KOR','H',7,'player','South Korea Player 7',TRUE,'original','regular'),('KOR8','national_team','KOR','H',8,'player','South Korea Player 8',TRUE,'original','regular'),('KOR9','national_team','KOR','H',9,'player','South Korea Player 9',TRUE,'original','regular'),('KOR10','national_team','KOR','H',10,'player','South Korea Player 10',TRUE,'original','regular'),('KOR11','national_team','KOR','H',11,'player','South Korea Player 11',TRUE,'original','regular'),('KOR12','national_team','KOR','H',12,'player','South Korea Player 12',TRUE,'original','regular'),('KOR13','national_team','KOR','H',13,'team_photo','South Korea Team Photo',TRUE,'original','regular'),('KOR14','national_team','KOR','H',14,'player','South Korea Player 14',TRUE,'original','regular'),('KOR15','national_team','KOR','H',15,'player','South Korea Player 15',TRUE,'original','regular'),('KOR16','national_team','KOR','H',16,'player','South Korea Player 16',TRUE,'original','regular'),('KOR17','national_team','KOR','H',17,'player','South Korea Player 17',TRUE,'original','regular'),('KOR18','national_team','KOR','H',18,'player','South Korea Player 18',TRUE,'original','regular'),('KOR19','national_team','KOR','H',19,'player','South Korea Player 19',TRUE,'original','regular'),('KOR20','national_team','KOR','H',20,'player','South Korea Player 20',TRUE,'original','regular')
ON CONFLICT (natural_key) DO NOTHING;

-- GROUP I: Colombia, Venezuela, Ecuador... (remaining groups)
-- GROUP I: Colombia, Venezuela, Paraguay, Chile
INSERT INTO stickers (natural_key, section_type, team_slug, group_code, position_in_section, position_role, sticker_name, is_official_album, release_batch, rarity) VALUES
('COL1','national_team','COL','I',1,'badge','Colombia Badge',TRUE,'original','regular'),('COL2','national_team','COL','I',2,'player','Colombia Player 2',TRUE,'original','regular'),('COL3','national_team','COL','I',3,'player','Colombia Player 3',TRUE,'original','regular'),('COL4','national_team','COL','I',4,'player','Colombia Player 4',TRUE,'original','regular'),('COL5','national_team','COL','I',5,'player','Colombia Player 5',TRUE,'original','regular'),('COL6','national_team','COL','I',6,'player','Colombia Player 6',TRUE,'original','regular'),('COL7','national_team','COL','I',7,'player','Colombia Player 7',TRUE,'original','regular'),('COL8','national_team','COL','I',8,'player','Colombia Player 8',TRUE,'original','regular'),('COL9','national_team','COL','I',9,'player','Colombia Player 9',TRUE,'original','regular'),('COL10','national_team','COL','I',10,'player','Colombia Player 10',TRUE,'original','regular'),('COL11','national_team','COL','I',11,'player','Colombia Player 11',TRUE,'original','regular'),('COL12','national_team','COL','I',12,'player','Colombia Player 12',TRUE,'original','regular'),('COL13','national_team','COL','I',13,'team_photo','Colombia Team Photo',TRUE,'original','regular'),('COL14','national_team','COL','I',14,'player','Colombia Player 14',TRUE,'original','regular'),('COL15','national_team','COL','I',15,'player','Colombia Player 15',TRUE,'original','regular'),('COL16','national_team','COL','I',16,'player','Colombia Player 16',TRUE,'original','regular'),('COL17','national_team','COL','I',17,'player','Colombia Player 17',TRUE,'original','regular'),('COL18','national_team','COL','I',18,'player','Colombia Player 18',TRUE,'original','regular'),('COL19','national_team','COL','I',19,'player','Colombia Player 19',TRUE,'original','regular'),('COL20','national_team','COL','I',20,'player','Colombia Player 20',TRUE,'original','regular'),
('VEN1','national_team','VEN','I',1,'badge','Venezuela Badge',TRUE,'original','regular'),('VEN2','national_team','VEN','I',2,'player','Venezuela Player 2',TRUE,'original','regular'),('VEN3','national_team','VEN','I',3,'player','Venezuela Player 3',TRUE,'original','regular'),('VEN4','national_team','VEN','I',4,'player','Venezuela Player 4',TRUE,'original','regular'),('VEN5','national_team','VEN','I',5,'player','Venezuela Player 5',TRUE,'original','regular'),('VEN6','national_team','VEN','I',6,'player','Venezuela Player 6',TRUE,'original','regular'),('VEN7','national_team','VEN','I',7,'player','Venezuela Player 7',TRUE,'original','regular'),('VEN8','national_team','VEN','I',8,'player','Venezuela Player 8',TRUE,'original','regular'),('VEN9','national_team','VEN','I',9,'player','Venezuela Player 9',TRUE,'original','regular'),('VEN10','national_team','VEN','I',10,'player','Venezuela Player 10',TRUE,'original','regular'),('VEN11','national_team','VEN','I',11,'player','Venezuela Player 11',TRUE,'original','regular'),('VEN12','national_team','VEN','I',12,'player','Venezuela Player 12',TRUE,'original','regular'),('VEN13','national_team','VEN','I',13,'team_photo','Venezuela Team Photo',TRUE,'original','regular'),('VEN14','national_team','VEN','I',14,'player','Venezuela Player 14',TRUE,'original','regular'),('VEN15','national_team','VEN','I',15,'player','Venezuela Player 15',TRUE,'original','regular'),('VEN16','national_team','VEN','I',16,'player','Venezuela Player 16',TRUE,'original','regular'),('VEN17','national_team','VEN','I',17,'player','Venezuela Player 17',TRUE,'original','regular'),('VEN18','national_team','VEN','I',18,'player','Venezuela Player 18',TRUE,'original','regular'),('VEN19','national_team','VEN','I',19,'player','Venezuela Player 19',TRUE,'original','regular'),('VEN20','national_team','VEN','I',20,'player','Venezuela Player 20',TRUE,'original','regular'),
('PAR1','national_team','PAR','I',1,'badge','Paraguay Badge',TRUE,'original','regular'),('PAR2','national_team','PAR','I',2,'player','Paraguay Player 2',TRUE,'original','regular'),('PAR3','national_team','PAR','I',3,'player','Paraguay Player 3',TRUE,'original','regular'),('PAR4','national_team','PAR','I',4,'player','Paraguay Player 4',TRUE,'original','regular'),('PAR5','national_team','PAR','I',5,'player','Paraguay Player 5',TRUE,'original','regular'),('PAR6','national_team','PAR','I',6,'player','Paraguay Player 6',TRUE,'original','regular'),('PAR7','national_team','PAR','I',7,'player','Paraguay Player 7',TRUE,'original','regular'),('PAR8','national_team','PAR','I',8,'player','Paraguay Player 8',TRUE,'original','regular'),('PAR9','national_team','PAR','I',9,'player','Paraguay Player 9',TRUE,'original','regular'),('PAR10','national_team','PAR','I',10,'player','Paraguay Player 10',TRUE,'original','regular'),('PAR11','national_team','PAR','I',11,'player','Paraguay Player 11',TRUE,'original','regular'),('PAR12','national_team','PAR','I',12,'player','Paraguay Player 12',TRUE,'original','regular'),('PAR13','national_team','PAR','I',13,'team_photo','Paraguay Team Photo',TRUE,'original','regular'),('PAR14','national_team','PAR','I',14,'player','Paraguay Player 14',TRUE,'original','regular'),('PAR15','national_team','PAR','I',15,'player','Paraguay Player 15',TRUE,'original','regular'),('PAR16','national_team','PAR','I',16,'player','Paraguay Player 16',TRUE,'original','regular'),('PAR17','national_team','PAR','I',17,'player','Paraguay Player 17',TRUE,'original','regular'),('PAR18','national_team','PAR','I',18,'player','Paraguay Player 18',TRUE,'original','regular'),('PAR19','national_team','PAR','I',19,'player','Paraguay Player 19',TRUE,'original','regular'),('PAR20','national_team','PAR','I',20,'player','Paraguay Player 20',TRUE,'original','regular'),
('CHI1','national_team','CHI','I',1,'badge','Chile Badge',TRUE,'original','regular'),('CHI2','national_team','CHI','I',2,'player','Chile Player 2',TRUE,'original','regular'),('CHI3','national_team','CHI','I',3,'player','Chile Player 3',TRUE,'original','regular'),('CHI4','national_team','CHI','I',4,'player','Chile Player 4',TRUE,'original','regular'),('CHI5','national_team','CHI','I',5,'player','Chile Player 5',TRUE,'original','regular'),('CHI6','national_team','CHI','I',6,'player','Chile Player 6',TRUE,'original','regular'),('CHI7','national_team','CHI','I',7,'player','Chile Player 7',TRUE,'original','regular'),('CHI8','national_team','CHI','I',8,'player','Chile Player 8',TRUE,'original','regular'),('CHI9','national_team','CHI','I',9,'player','Chile Player 9',TRUE,'original','regular'),('CHI10','national_team','CHI','I',10,'player','Chile Player 10',TRUE,'original','regular'),('CHI11','national_team','CHI','I',11,'player','Chile Player 11',TRUE,'original','regular'),('CHI12','national_team','CHI','I',12,'player','Chile Player 12',TRUE,'original','regular'),('CHI13','national_team','CHI','I',13,'team_photo','Chile Team Photo',TRUE,'original','regular'),('CHI14','national_team','CHI','I',14,'player','Chile Player 14',TRUE,'original','regular'),('CHI15','national_team','CHI','I',15,'player','Chile Player 15',TRUE,'original','regular'),('CHI16','national_team','CHI','I',16,'player','Chile Player 16',TRUE,'original','regular'),('CHI17','national_team','CHI','I',17,'player','Chile Player 17',TRUE,'original','regular'),('CHI18','national_team','CHI','I',18,'player','Chile Player 18',TRUE,'original','regular'),('CHI19','national_team','CHI','I',19,'player','Chile Player 19',TRUE,'original','regular'),('CHI20','national_team','CHI','I',20,'player','Chile Player 20',TRUE,'original','regular')
ON CONFLICT (natural_key) DO NOTHING;

-- GROUP J: Mexico... (4 more teams)
-- GROUP J: Algeria, Nigeria, Ivory Coast, South Africa
INSERT INTO stickers (natural_key, section_type, team_slug, group_code, position_in_section, position_role, sticker_name, is_official_album, release_batch, rarity) VALUES
('ALG1','national_team','ALG','J',1,'badge','Algeria Badge',TRUE,'original','regular'),('ALG2','national_team','ALG','J',2,'player','Algeria Player 2',TRUE,'original','regular'),('ALG3','national_team','ALG','J',3,'player','Algeria Player 3',TRUE,'original','regular'),('ALG4','national_team','ALG','J',4,'player','Algeria Player 4',TRUE,'original','regular'),('ALG5','national_team','ALG','J',5,'player','Algeria Player 5',TRUE,'original','regular'),('ALG6','national_team','ALG','J',6,'player','Algeria Player 6',TRUE,'original','regular'),('ALG7','national_team','ALG','J',7,'player','Algeria Player 7',TRUE,'original','regular'),('ALG8','national_team','ALG','J',8,'player','Algeria Player 8',TRUE,'original','regular'),('ALG9','national_team','ALG','J',9,'player','Algeria Player 9',TRUE,'original','regular'),('ALG10','national_team','ALG','J',10,'player','Algeria Player 10',TRUE,'original','regular'),('ALG11','national_team','ALG','J',11,'player','Algeria Player 11',TRUE,'original','regular'),('ALG12','national_team','ALG','J',12,'player','Algeria Player 12',TRUE,'original','regular'),('ALG13','national_team','ALG','J',13,'team_photo','Algeria Team Photo',TRUE,'original','regular'),('ALG14','national_team','ALG','J',14,'player','Algeria Player 14',TRUE,'original','regular'),('ALG15','national_team','ALG','J',15,'player','Algeria Player 15',TRUE,'original','regular'),('ALG16','national_team','ALG','J',16,'player','Algeria Player 16',TRUE,'original','regular'),('ALG17','national_team','ALG','J',17,'player','Algeria Player 17',TRUE,'original','regular'),('ALG18','national_team','ALG','J',18,'player','Algeria Player 18',TRUE,'original','regular'),('ALG19','national_team','ALG','J',19,'player','Algeria Player 19',TRUE,'original','regular'),('ALG20','national_team','ALG','J',20,'player','Algeria Player 20',TRUE,'original','regular'),
('NGA1','national_team','NGA','J',1,'badge','Nigeria Badge',TRUE,'original','regular'),('NGA2','national_team','NGA','J',2,'player','Nigeria Player 2',TRUE,'original','regular'),('NGA3','national_team','NGA','J',3,'player','Nigeria Player 3',TRUE,'original','regular'),('NGA4','national_team','NGA','J',4,'player','Nigeria Player 4',TRUE,'original','regular'),('NGA5','national_team','NGA','J',5,'player','Nigeria Player 5',TRUE,'original','regular'),('NGA6','national_team','NGA','J',6,'player','Nigeria Player 6',TRUE,'original','regular'),('NGA7','national_team','NGA','J',7,'player','Nigeria Player 7',TRUE,'original','regular'),('NGA8','national_team','NGA','J',8,'player','Nigeria Player 8',TRUE,'original','regular'),('NGA9','national_team','NGA','J',9,'player','Nigeria Player 9',TRUE,'original','regular'),('NGA10','national_team','NGA','J',10,'player','Nigeria Player 10',TRUE,'original','regular'),('NGA11','national_team','NGA','J',11,'player','Nigeria Player 11',TRUE,'original','regular'),('NGA12','national_team','NGA','J',12,'player','Nigeria Player 12',TRUE,'original','regular'),('NGA13','national_team','NGA','J',13,'team_photo','Nigeria Team Photo',TRUE,'original','regular'),('NGA14','national_team','NGA','J',14,'player','Nigeria Player 14',TRUE,'original','regular'),('NGA15','national_team','NGA','J',15,'player','Nigeria Player 15',TRUE,'original','regular'),('NGA16','national_team','NGA','J',16,'player','Nigeria Player 16',TRUE,'original','regular'),('NGA17','national_team','NGA','J',17,'player','Nigeria Player 17',TRUE,'original','regular'),('NGA18','national_team','NGA','J',18,'player','Nigeria Player 18',TRUE,'original','regular'),('NGA19','national_team','NGA','J',19,'player','Nigeria Player 19',TRUE,'original','regular'),('NGA20','national_team','NGA','J',20,'player','Nigeria Player 20',TRUE,'original','regular'),
('CIV1','national_team','CIV','J',1,'badge','Ivory Coast Badge',TRUE,'original','regular'),('CIV2','national_team','CIV','J',2,'player','Ivory Coast Player 2',TRUE,'original','regular'),('CIV3','national_team','CIV','J',3,'player','Ivory Coast Player 3',TRUE,'original','regular'),('CIV4','national_team','CIV','J',4,'player','Ivory Coast Player 4',TRUE,'original','regular'),('CIV5','national_team','CIV','J',5,'player','Ivory Coast Player 5',TRUE,'original','regular'),('CIV6','national_team','CIV','J',6,'player','Ivory Coast Player 6',TRUE,'original','regular'),('CIV7','national_team','CIV','J',7,'player','Ivory Coast Player 7',TRUE,'original','regular'),('CIV8','national_team','CIV','J',8,'player','Ivory Coast Player 8',TRUE,'original','regular'),('CIV9','national_team','CIV','J',9,'player','Ivory Coast Player 9',TRUE,'original','regular'),('CIV10','national_team','CIV','J',10,'player','Ivory Coast Player 10',TRUE,'original','regular'),('CIV11','national_team','CIV','J',11,'player','Ivory Coast Player 11',TRUE,'original','regular'),('CIV12','national_team','CIV','J',12,'player','Ivory Coast Player 12',TRUE,'original','regular'),('CIV13','national_team','CIV','J',13,'team_photo','Ivory Coast Team Photo',TRUE,'original','regular'),('CIV14','national_team','CIV','J',14,'player','Ivory Coast Player 14',TRUE,'original','regular'),('CIV15','national_team','CIV','J',15,'player','Ivory Coast Player 15',TRUE,'original','regular'),('CIV16','national_team','CIV','J',16,'player','Ivory Coast Player 16',TRUE,'original','regular'),('CIV17','national_team','CIV','J',17,'player','Ivory Coast Player 17',TRUE,'original','regular'),('CIV18','national_team','CIV','J',18,'player','Ivory Coast Player 18',TRUE,'original','regular'),('CIV19','national_team','CIV','J',19,'player','Ivory Coast Player 19',TRUE,'original','regular'),('CIV20','national_team','CIV','J',20,'player','Ivory Coast Player 20',TRUE,'original','regular'),
('RSA1','national_team','RSA','J',1,'badge','South Africa Badge',TRUE,'original','regular'),('RSA2','national_team','RSA','J',2,'player','South Africa Player 2',TRUE,'original','regular'),('RSA3','national_team','RSA','J',3,'player','South Africa Player 3',TRUE,'original','regular'),('RSA4','national_team','RSA','J',4,'player','South Africa Player 4',TRUE,'original','regular'),('RSA5','national_team','RSA','J',5,'player','South Africa Player 5',TRUE,'original','regular'),('RSA6','national_team','RSA','J',6,'player','South Africa Player 6',TRUE,'original','regular'),('RSA7','national_team','RSA','J',7,'player','South Africa Player 7',TRUE,'original','regular'),('RSA8','national_team','RSA','J',8,'player','South Africa Player 8',TRUE,'original','regular'),('RSA9','national_team','RSA','J',9,'player','South Africa Player 9',TRUE,'original','regular'),('RSA10','national_team','RSA','J',10,'player','South Africa Player 10',TRUE,'original','regular'),('RSA11','national_team','RSA','J',11,'player','South Africa Player 11',TRUE,'original','regular'),('RSA12','national_team','RSA','J',12,'player','South Africa Player 12',TRUE,'original','regular'),('RSA13','national_team','RSA','J',13,'team_photo','South Africa Team Photo',TRUE,'original','regular'),('RSA14','national_team','RSA','J',14,'player','South Africa Player 14',TRUE,'original','regular'),('RSA15','national_team','RSA','J',15,'player','South Africa Player 15',TRUE,'original','regular'),('RSA16','national_team','RSA','J',16,'player','South Africa Player 16',TRUE,'original','regular'),('RSA17','national_team','RSA','J',17,'player','South Africa Player 17',TRUE,'original','regular'),('RSA18','national_team','RSA','J',18,'player','South Africa Player 18',TRUE,'original','regular'),('RSA19','national_team','RSA','J',19,'player','South Africa Player 19',TRUE,'original','regular'),('RSA20','national_team','RSA','J',20,'player','South Africa Player 20',TRUE,'original','regular')
ON CONFLICT (natural_key) DO NOTHING;

-- GROUP K: New Zealand, Indonesia, Iraq, Saudi Arabia... (4 teams from Asia/Oceania)
-- GROUP K: Japan... actually let me use: Turkey, Greece, Albania, Slovakia
INSERT INTO stickers (natural_key, section_type, team_slug, group_code, position_in_section, position_role, sticker_name, is_official_album, release_batch, rarity) VALUES
('TUR1','national_team','TUR','K',1,'badge','Turkey Badge',TRUE,'original','regular'),('TUR2','national_team','TUR','K',2,'player','Turkey Player 2',TRUE,'original','regular'),('TUR3','national_team','TUR','K',3,'player','Turkey Player 3',TRUE,'original','regular'),('TUR4','national_team','TUR','K',4,'player','Turkey Player 4',TRUE,'original','regular'),('TUR5','national_team','TUR','K',5,'player','Turkey Player 5',TRUE,'original','regular'),('TUR6','national_team','TUR','K',6,'player','Turkey Player 6',TRUE,'original','regular'),('TUR7','national_team','TUR','K',7,'player','Turkey Player 7',TRUE,'original','regular'),('TUR8','national_team','TUR','K',8,'player','Turkey Player 8',TRUE,'original','regular'),('TUR9','national_team','TUR','K',9,'player','Turkey Player 9',TRUE,'original','regular'),('TUR10','national_team','TUR','K',10,'player','Turkey Player 10',TRUE,'original','regular'),('TUR11','national_team','TUR','K',11,'player','Turkey Player 11',TRUE,'original','regular'),('TUR12','national_team','TUR','K',12,'player','Turkey Player 12',TRUE,'original','regular'),('TUR13','national_team','TUR','K',13,'team_photo','Turkey Team Photo',TRUE,'original','regular'),('TUR14','national_team','TUR','K',14,'player','Turkey Player 14',TRUE,'original','regular'),('TUR15','national_team','TUR','K',15,'player','Turkey Player 15',TRUE,'original','regular'),('TUR16','national_team','TUR','K',16,'player','Turkey Player 16',TRUE,'original','regular'),('TUR17','national_team','TUR','K',17,'player','Turkey Player 17',TRUE,'original','regular'),('TUR18','national_team','TUR','K',18,'player','Turkey Player 18',TRUE,'original','regular'),('TUR19','national_team','TUR','K',19,'player','Turkey Player 19',TRUE,'original','regular'),('TUR20','national_team','TUR','K',20,'player','Turkey Player 20',TRUE,'original','regular'),
('GRE1','national_team','GRE','K',1,'badge','Greece Badge',TRUE,'original','regular'),('GRE2','national_team','GRE','K',2,'player','Greece Player 2',TRUE,'original','regular'),('GRE3','national_team','GRE','K',3,'player','Greece Player 3',TRUE,'original','regular'),('GRE4','national_team','GRE','K',4,'player','Greece Player 4',TRUE,'original','regular'),('GRE5','national_team','GRE','K',5,'player','Greece Player 5',TRUE,'original','regular'),('GRE6','national_team','GRE','K',6,'player','Greece Player 6',TRUE,'original','regular'),('GRE7','national_team','GRE','K',7,'player','Greece Player 7',TRUE,'original','regular'),('GRE8','national_team','GRE','K',8,'player','Greece Player 8',TRUE,'original','regular'),('GRE9','national_team','GRE','K',9,'player','Greece Player 9',TRUE,'original','regular'),('GRE10','national_team','GRE','K',10,'player','Greece Player 10',TRUE,'original','regular'),('GRE11','national_team','GRE','K',11,'player','Greece Player 11',TRUE,'original','regular'),('GRE12','national_team','GRE','K',12,'player','Greece Player 12',TRUE,'original','regular'),('GRE13','national_team','GRE','K',13,'team_photo','Greece Team Photo',TRUE,'original','regular'),('GRE14','national_team','GRE','K',14,'player','Greece Player 14',TRUE,'original','regular'),('GRE15','national_team','GRE','K',15,'player','Greece Player 15',TRUE,'original','regular'),('GRE16','national_team','GRE','K',16,'player','Greece Player 16',TRUE,'original','regular'),('GRE17','national_team','GRE','K',17,'player','Greece Player 17',TRUE,'original','regular'),('GRE18','national_team','GRE','K',18,'player','Greece Player 18',TRUE,'original','regular'),('GRE19','national_team','GRE','K',19,'player','Greece Player 19',TRUE,'original','regular'),('GRE20','national_team','GRE','K',20,'player','Greece Player 20',TRUE,'original','regular'),
('ALB1','national_team','ALB','K',1,'badge','Albania Badge',TRUE,'original','regular'),('ALB2','national_team','ALB','K',2,'player','Albania Player 2',TRUE,'original','regular'),('ALB3','national_team','ALB','K',3,'player','Albania Player 3',TRUE,'original','regular'),('ALB4','national_team','ALB','K',4,'player','Albania Player 4',TRUE,'original','regular'),('ALB5','national_team','ALB','K',5,'player','Albania Player 5',TRUE,'original','regular'),('ALB6','national_team','ALB','K',6,'player','Albania Player 6',TRUE,'original','regular'),('ALB7','national_team','ALB','K',7,'player','Albania Player 7',TRUE,'original','regular'),('ALB8','national_team','ALB','K',8,'player','Albania Player 8',TRUE,'original','regular'),('ALB9','national_team','ALB','K',9,'player','Albania Player 9',TRUE,'original','regular'),('ALB10','national_team','ALB','K',10,'player','Albania Player 10',TRUE,'original','regular'),('ALB11','national_team','ALB','K',11,'player','Albania Player 11',TRUE,'original','regular'),('ALB12','national_team','ALB','K',12,'player','Albania Player 12',TRUE,'original','regular'),('ALB13','national_team','ALB','K',13,'team_photo','Albania Team Photo',TRUE,'original','regular'),('ALB14','national_team','ALB','K',14,'player','Albania Player 14',TRUE,'original','regular'),('ALB15','national_team','ALB','K',15,'player','Albania Player 15',TRUE,'original','regular'),('ALB16','national_team','ALB','K',16,'player','Albania Player 16',TRUE,'original','regular'),('ALB17','national_team','ALB','K',17,'player','Albania Player 17',TRUE,'original','regular'),('ALB18','national_team','ALB','K',18,'player','Albania Player 18',TRUE,'original','regular'),('ALB19','national_team','ALB','K',19,'player','Albania Player 19',TRUE,'original','regular'),('ALB20','national_team','ALB','K',20,'player','Albania Player 20',TRUE,'original','regular'),
('SVK1','national_team','SVK','K',1,'badge','Slovakia Badge',TRUE,'original','regular'),('SVK2','national_team','SVK','K',2,'player','Slovakia Player 2',TRUE,'original','regular'),('SVK3','national_team','SVK','K',3,'player','Slovakia Player 3',TRUE,'original','regular'),('SVK4','national_team','SVK','K',4,'player','Slovakia Player 4',TRUE,'original','regular'),('SVK5','national_team','SVK','K',5,'player','Slovakia Player 5',TRUE,'original','regular'),('SVK6','national_team','SVK','K',6,'player','Slovakia Player 6',TRUE,'original','regular'),('SVK7','national_team','SVK','K',7,'player','Slovakia Player 7',TRUE,'original','regular'),('SVK8','national_team','SVK','K',8,'player','Slovakia Player 8',TRUE,'original','regular'),('SVK9','national_team','SVK','K',9,'player','Slovakia Player 9',TRUE,'original','regular'),('SVK10','national_team','SVK','K',10,'player','Slovakia Player 10',TRUE,'original','regular'),('SVK11','national_team','SVK','K',11,'player','Slovakia Player 11',TRUE,'original','regular'),('SVK12','national_team','SVK','K',12,'player','Slovakia Player 12',TRUE,'original','regular'),('SVK13','national_team','SVK','K',13,'team_photo','Slovakia Team Photo',TRUE,'original','regular'),('SVK14','national_team','SVK','K',14,'player','Slovakia Player 14',TRUE,'original','regular'),('SVK15','national_team','SVK','K',15,'player','Slovakia Player 15',TRUE,'original','regular'),('SVK16','national_team','SVK','K',16,'player','Slovakia Player 16',TRUE,'original','regular'),('SVK17','national_team','SVK','K',17,'player','Slovakia Player 17',TRUE,'original','regular'),('SVK18','national_team','SVK','K',18,'player','Slovakia Player 18',TRUE,'original','regular'),('SVK19','national_team','SVK','K',19,'player','Slovakia Player 19',TRUE,'original','regular'),('SVK20','national_team','SVK','K',20,'player','Slovakia Player 20',TRUE,'original','regular')
ON CONFLICT (natural_key) DO NOTHING;

-- GROUP L: New Zealand, Indonesia, Iraq, Uzbekistan
INSERT INTO stickers (natural_key, section_type, team_slug, group_code, position_in_section, position_role, sticker_name, is_official_album, release_batch, rarity) VALUES
('NZL1','national_team','NZL','L',1,'badge','New Zealand Badge',TRUE,'original','regular'),('NZL2','national_team','NZL','L',2,'player','New Zealand Player 2',TRUE,'original','regular'),('NZL3','national_team','NZL','L',3,'player','New Zealand Player 3',TRUE,'original','regular'),('NZL4','national_team','NZL','L',4,'player','New Zealand Player 4',TRUE,'original','regular'),('NZL5','national_team','NZL','L',5,'player','New Zealand Player 5',TRUE,'original','regular'),('NZL6','national_team','NZL','L',6,'player','New Zealand Player 6',TRUE,'original','regular'),('NZL7','national_team','NZL','L',7,'player','New Zealand Player 7',TRUE,'original','regular'),('NZL8','national_team','NZL','L',8,'player','New Zealand Player 8',TRUE,'original','regular'),('NZL9','national_team','NZL','L',9,'player','New Zealand Player 9',TRUE,'original','regular'),('NZL10','national_team','NZL','L',10,'player','New Zealand Player 10',TRUE,'original','regular'),('NZL11','national_team','NZL','L',11,'player','New Zealand Player 11',TRUE,'original','regular'),('NZL12','national_team','NZL','L',12,'player','New Zealand Player 12',TRUE,'original','regular'),('NZL13','national_team','NZL','L',13,'team_photo','New Zealand Team Photo',TRUE,'original','regular'),('NZL14','national_team','NZL','L',14,'player','New Zealand Player 14',TRUE,'original','regular'),('NZL15','national_team','NZL','L',15,'player','New Zealand Player 15',TRUE,'original','regular'),('NZL16','national_team','NZL','L',16,'player','New Zealand Player 16',TRUE,'original','regular'),('NZL17','national_team','NZL','L',17,'player','New Zealand Player 17',TRUE,'original','regular'),('NZL18','national_team','NZL','L',18,'player','New Zealand Player 18',TRUE,'original','regular'),('NZL19','national_team','NZL','L',19,'player','New Zealand Player 19',TRUE,'original','regular'),('NZL20','national_team','NZL','L',20,'player','New Zealand Player 20',TRUE,'original','regular'),
('IDN1','national_team','IDN','L',1,'badge','Indonesia Badge',TRUE,'original','regular'),('IDN2','national_team','IDN','L',2,'player','Indonesia Player 2',TRUE,'original','regular'),('IDN3','national_team','IDN','L',3,'player','Indonesia Player 3',TRUE,'original','regular'),('IDN4','national_team','IDN','L',4,'player','Indonesia Player 4',TRUE,'original','regular'),('IDN5','national_team','IDN','L',5,'player','Indonesia Player 5',TRUE,'original','regular'),('IDN6','national_team','IDN','L',6,'player','Indonesia Player 6',TRUE,'original','regular'),('IDN7','national_team','IDN','L',7,'player','Indonesia Player 7',TRUE,'original','regular'),('IDN8','national_team','IDN','L',8,'player','Indonesia Player 8',TRUE,'original','regular'),('IDN9','national_team','IDN','L',9,'player','Indonesia Player 9',TRUE,'original','regular'),('IDN10','national_team','IDN','L',10,'player','Indonesia Player 10',TRUE,'original','regular'),('IDN11','national_team','IDN','L',11,'player','Indonesia Player 11',TRUE,'original','regular'),('IDN12','national_team','IDN','L',12,'player','Indonesia Player 12',TRUE,'original','regular'),('IDN13','national_team','IDN','L',13,'team_photo','Indonesia Team Photo',TRUE,'original','regular'),('IDN14','national_team','IDN','L',14,'player','Indonesia Player 14',TRUE,'original','regular'),('IDN15','national_team','IDN','L',15,'player','Indonesia Player 15',TRUE,'original','regular'),('IDN16','national_team','IDN','L',16,'player','Indonesia Player 16',TRUE,'original','regular'),('IDN17','national_team','IDN','L',17,'player','Indonesia Player 17',TRUE,'original','regular'),('IDN18','national_team','IDN','L',18,'player','Indonesia Player 18',TRUE,'original','regular'),('IDN19','national_team','IDN','L',19,'player','Indonesia Player 19',TRUE,'original','regular'),('IDN20','national_team','IDN','L',20,'player','Indonesia Player 20',TRUE,'original','regular'),
('IRQ1','national_team','IRQ','L',1,'badge','Iraq Badge',TRUE,'original','regular'),('IRQ2','national_team','IRQ','L',2,'player','Iraq Player 2',TRUE,'original','regular'),('IRQ3','national_team','IRQ','L',3,'player','Iraq Player 3',TRUE,'original','regular'),('IRQ4','national_team','IRQ','L',4,'player','Iraq Player 4',TRUE,'original','regular'),('IRQ5','national_team','IRQ','L',5,'player','Iraq Player 5',TRUE,'original','regular'),('IRQ6','national_team','IRQ','L',6,'player','Iraq Player 6',TRUE,'original','regular'),('IRQ7','national_team','IRQ','L',7,'player','Iraq Player 7',TRUE,'original','regular'),('IRQ8','national_team','IRQ','L',8,'player','Iraq Player 8',TRUE,'original','regular'),('IRQ9','national_team','IRQ','L',9,'player','Iraq Player 9',TRUE,'original','regular'),('IRQ10','national_team','IRQ','L',10,'player','Iraq Player 10',TRUE,'original','regular'),('IRQ11','national_team','IRQ','L',11,'player','Iraq Player 11',TRUE,'original','regular'),('IRQ12','national_team','IRQ','L',12,'player','Iraq Player 12',TRUE,'original','regular'),('IRQ13','national_team','IRQ','L',13,'team_photo','Iraq Team Photo',TRUE,'original','regular'),('IRQ14','national_team','IRQ','L',14,'player','Iraq Player 14',TRUE,'original','regular'),('IRQ15','national_team','IRQ','L',15,'player','Iraq Player 15',TRUE,'original','regular'),('IRQ16','national_team','IRQ','L',16,'player','Iraq Player 16',TRUE,'original','regular'),('IRQ17','national_team','IRQ','L',17,'player','Iraq Player 17',TRUE,'original','regular'),('IRQ18','national_team','IRQ','L',18,'player','Iraq Player 18',TRUE,'original','regular'),('IRQ19','national_team','IRQ','L',19,'player','Iraq Player 19',TRUE,'original','regular'),('IRQ20','national_team','IRQ','L',20,'player','Iraq Player 20',TRUE,'original','regular'),
('UZB1','national_team','UZB','L',1,'badge','Uzbekistan Badge',TRUE,'original','regular'),('UZB2','national_team','UZB','L',2,'player','Uzbekistan Player 2',TRUE,'original','regular'),('UZB3','national_team','UZB','L',3,'player','Uzbekistan Player 3',TRUE,'original','regular'),('UZB4','national_team','UZB','L',4,'player','Uzbekistan Player 4',TRUE,'original','regular'),('UZB5','national_team','UZB','L',5,'player','Uzbekistan Player 5',TRUE,'original','regular'),('UZB6','national_team','UZB','L',6,'player','Uzbekistan Player 6',TRUE,'original','regular'),('UZB7','national_team','UZB','L',7,'player','Uzbekistan Player 7',TRUE,'original','regular'),('UZB8','national_team','UZB','L',8,'player','Uzbekistan Player 8',TRUE,'original','regular'),('UZB9','national_team','UZB','L',9,'player','Uzbekistan Player 9',TRUE,'original','regular'),('UZB10','national_team','UZB','L',10,'player','Uzbekistan Player 10',TRUE,'original','regular'),('UZB11','national_team','UZB','L',11,'player','Uzbekistan Player 11',TRUE,'original','regular'),('UZB12','national_team','UZB','L',12,'player','Uzbekistan Player 12',TRUE,'original','regular'),('UZB13','national_team','UZB','L',13,'team_photo','Uzbekistan Team Photo',TRUE,'original','regular'),('UZB14','national_team','UZB','L',14,'player','Uzbekistan Player 14',TRUE,'original','regular'),('UZB15','national_team','UZB','L',15,'player','Uzbekistan Player 15',TRUE,'original','regular'),('UZB16','national_team','UZB','L',16,'player','Uzbekistan Player 16',TRUE,'original','regular'),('UZB17','national_team','UZB','L',17,'player','Uzbekistan Player 17',TRUE,'original','regular'),('UZB18','national_team','UZB','L',18,'player','Uzbekistan Player 18',TRUE,'original','regular'),('UZB19','national_team','UZB','L',19,'player','Uzbekistan Player 19',TRUE,'original','regular'),('UZB20','national_team','UZB','L',20,'player','Uzbekistan Player 20',TRUE,'original','regular')
ON CONFLICT (natural_key) DO NOTHING;
